---
title: "R Notebook"
output:
  html_document:
    df_print: paged
params:
  config: '../../config/config.yaml'
  out_prefix: "~/mount/CT/git_test/results/" #'results/'
  antibody: 'Olig2'
  window: 5000
---

```{r libraries}
#suppressPackageStartupMessages
library(Seurat,quietly = TRUE,warn.conflicts = FALSE)
library(gridExtra,quietly = TRUE,warn.conflicts = FALSE)
library(dplyr,quietly = TRUE,warn.conflicts = FALSE)
library(Signac,quietly = TRUE,warn.conflicts = FALSE)
library(EnsDb.Mmusculus.v79,quietly = TRUE,warn.conflicts = FALSE)
library(ggplot2,quietly = TRUE,warn.conflicts = FALSE)
library(RColorBrewer,quietly = TRUE,warn.conflicts = FALSE)
library(rtracklayer,quietly = TRUE,warn.conflicts = FALSE)
library(yaml,quietly = TRUE,warn.conflicts = FALSE)
library(pheatmap,quietly = TRUE,warn.conflicts = FALSE)


set.seed(100)
```


# Read config

```{r read_config}
source("../../scripts/R/func.R")
config <- yaml::read_yaml(params$config)

assay <- paste0("bins_",params$window)
```

# load annotations

```{r load_gene_annotations}
genebodyandpromoter.coords.flat <- load_ensembl_annot(config$general$Version)
```


```{r create_out_directories}
dir.create(paste0(params$out_prefix,params$antibody,"/clustering/bigwig/clusters_all/"),recursive = TRUE)
dir.create(paste0(params$out_prefix,params$antibody,"/clustering/markers_bed/"),recursive = TRUE)
dir.create(paste0(params$out_prefix,params$antibody,'/clustering/bam_per_cluster/'))
```


# Reduce dimensionality with LSI and plot the loadings

```{r load_and_merge}
samples <- names(which(unlist(lapply(config$samples,function(x){x$Antibody == params$antibody}))))
assay = paste0('bins_',params$window)


brain.ls <- lapply(samples,function(x){
  # Read the seurat object
  brain                     <- readRDS(paste0(params$out_prefix,x,'/seurat/bin_',params$window,'/Seurat_object.Rds'))
  DefaultAssay(brain)       <- assay
  brain
})

brain.merged <- Reduce(function(x,y) merge(x,y), brain.ls)
```


```{r filter_lowUMI}
brain.merged  <- brain.merged[,brain.merged$logUMI > 1.0]

# Blacklist
rows.pass             <- GRangesToString(subsetByOverlaps(x = StringToGRanges(rownames(brain.merged)),ranges = blacklist_mm10,invert = TRUE))
bins.mat              <- brain.merged[[assay]]@counts[rownames(brain.merged) %in% rows.pass,]

brain.merged[[assay]] <- CreateAssayObject(counts = bins.mat)
```


```{r cluster_and_dimreduce}
# Re-do the dimreduction
DefaultAssay(brain.merged) <- assay

brain.merged <- RunTFIDF(brain.merged)
brain.merged <- FindTopFeatures(brain.merged, min.cutoff = 'q10')
  
brain.merged <- RunSVD(
  object = brain.merged,
  assay = assay,
  reduction.key = 'LSI_',
  reduction.name = 'lsi'
)
  
brain.merged <- RunUMAP(
  object = brain.merged,
  reduction = 'lsi',
  dims = 2:15
)

brain.merged <- FindNeighbors(
  object = brain.merged,
  reduction = 'lsi',
  dims = 2:20
)
brain.merged <- FindClusters(
  object = brain.merged,
  algorithm = 3,
  resolution = 0.2,
  verbose = FALSE
)
  
DimPlot(brain.merged,label=TRUE)
DimPlot(brain.merged,group.by='sample') + theme(legend.position = 'bottom')

```

# Dimensionality reduction using peaks gives similar results

```{r peaks_dimreduce,eval=FALSE}
peaks <- rtracklayer::import(paste0(params$out_prefix,'/merged/',params$antibody,'/macs/narrow/',params$antibody,'_peaks.narrowPeak'))
peaks <- subsetByOverlaps(x = peaks,ranges =  blacklist_mm10,invert = TRUE)

fragments <- paste0(params$out_prefix,unique(brain.merged$orig.ident),'/outs/fragments.tsv.gz')
names(fragments) <- unique(brain.merged$orig.ident)


peak.matrix.ls <- lapply(names(fragments),function(x){
  FeatureMatrix(fragments = fragments[x],features = peaks,cells = colnames(brain.merged[,brain.merged$orig.ident == x]))
})

rows.summary <- table(unlist(lapply(peak.matrix.ls,rownames))) 
common.rows  <- names(rows.summary[rows.summary == length(peak.matrix.ls)])

peak.matrix.ls<-  lapply(peak.matrix.ls,function(x){
  x[common.rows,]
})

peak.matrix.merged <- do.call(cbind,peak.matrix.ls)

brain.merged[['peaks']] <- CreateAssayObject(counts = peak.matrix.merged)


assay <- 'peaks'
DefaultAssay(brain.merged) <- assay
brain.merged <- RunTFIDF(brain.merged)
brain.merged <- FindTopFeatures(brain.merged, min.cutoff = 'q0')
  
brain.merged <- RunSVD(
  object = brain.merged,
  assay = assay,
  reduction.key = 'LSI_',
  reduction.name = 'lsi'
)
  
brain.merged <- RunUMAP(
  object = brain.merged,
  reduction = 'lsi',
  dims = 2:20
)

  
DimPlot(brain.merged,label=TRUE)
DimPlot(brain.merged,group.by='sample') + theme(legend.position = 'bottom')
```



```{r plots, fig.width=12,fig.height=6}

p1 <- DimPlot(brain.merged,group.by='sample') + NoLegend() + theme(legend.position = 'bottom')
p2 <- DimPlot(brain.merged,label=TRUE)+ NoLegend()

p3 <- DimPlot(brain.merged,group.by = 'Age') + theme(legend.position = 'bottom')
p4 <- DimPlot(brain.merged,group.by = 'GFP') + scale_color_manual(values = brewer.pal(name = 'Set1',n = 9)[c(4,3)]) + theme(legend.position = 'bottom')


p.ls <- lapply(unique(brain.merged$sample),function(x){
  to_plot <- brain.merged[,brain.merged$sample == x]
  DimPlot(to_plot,label=TRUE,pt.size=0.3)+ NoLegend() + ggtitle(paste(x,unique(to_plot$Age), unique(to_plot$GFP))) + theme(plot.title = element_text(size=12)) + coord_cartesian(xlim=c(-10,10),ylim=c(-7,7))
})

FeaturePlot(brain.merged,'logUMI',max.cutoff = 3) + scale_color_viridis_c() 
p1 + p2
p3 + p4

do.call(grid.arrange,c(p.ls,nrow=1))
```


```{r load_RNA_markers}
markers <- read.csv2(file=paste0(params$out_prefix,'Sox10_RNA/clustering/GFP/markers.csv'),row.names = 1)
```



```{r Plot_RNA_modules_projection,fig.width=6,fig.height=6}
assay='GA'

brain.markers.ls <- lapply(unique(markers$cluster),function(x){
  marker.genes <- markers[markers$cluster==x & markers$p_val_adj < 0.05 & markers$avg_logFC > 0,"gene"]
  marker.genes <- head(marker.genes,200)
  marker.genes.agg.exp <- Matrix::colSums(brain.merged[[assay]]@counts[rownames(brain.merged[[assay]]) %in% marker.genes,])
  marker.genes.agg.exp <- marker.genes.agg.exp[marker.genes.agg.exp > 1]
  marker.genes.agg.exp <- marker.genes.agg.exp / Matrix::colSums(brain.merged[[assay]]@counts)[names(marker.genes.agg.exp)]
  return(marker.genes.agg.exp)
})

names(brain.markers.ls)  <- gsub("-",".",unique(markers$cluster))
markers.agg.df           <- do.call(cbind,brain.markers.ls)
colnames(markers.agg.df) <- paste0("marker_",gsub(" ",".",colnames(markers.agg.df)))


brain.merged <- AddMetaData(brain.merged,metadata = markers.agg.df,col.name = colnames(markers.agg.df))



lapply(as.character(colnames(markers.agg.df)),function(x){
  FeaturePlot(brain.merged,x,max.cutoff = quantile(markers.agg.df[,x],0.95,na.rm=TRUE),min.cutoff = quantile(markers.agg.df[,x],0.05,na.rm=TRUE),pt.size = 1) + scale_color_viridis_c() 
  #FeaturePlot(brain,x,max.cutoff = 0.08,min.cutoff = 0.02) + scale_color_viridis_c(limits=c(0.02,0.08)) 
  })


```


```{r Plot_H3K27ac_modules_projection,fig.width=3,fig.height=3, eval=FALSE}
markers <- read.csv2(file=paste0(params$out_prefix,'H3K27ac/clustering/markers_top.csv'),row.names = 1)
assay='bins_5000'

brain.markers.ls <- lapply(unique(markers$cluster),function(x){
  marker.genes <- markers[markers$cluster==x & markers$p_val_adj < 0.05 & markers$avg_logFC > 0,"gene"]
  marker.genes <- head(marker.genes,500)
  marker.genes.agg.exp <- Matrix::colSums(brain.merged[[assay]]@counts[rownames(brain.merged[[assay]]) %in% marker.genes,])
  #marker.genes.agg.exp <- marker.genes.agg.exp[marker.genes.agg.exp > 1]
  marker.genes.agg.exp <- marker.genes.agg.exp / Matrix::colSums(brain.merged[[assay]]@counts)[names(marker.genes.agg.exp)]
  return(marker.genes.agg.exp)
})

names(brain.markers.ls)  <- gsub("-",".",unique(markers$cluster))
markers.agg.df           <- do.call(cbind,brain.markers.ls)
colnames(markers.agg.df) <- paste0("marker_",gsub(" ",".",colnames(markers.agg.df)))


brain.merged <- AddMetaData(brain.merged,metadata = markers.agg.df,col.name = colnames(markers.agg.df))



lapply(as.character(colnames(markers.agg.df)),function(x){
  FeaturePlot(brain.merged,x,max.cutoff = quantile(markers.agg.df[,x],0.99,na.rm=TRUE),min.cutoff = quantile(markers.agg.df[,x],0.05,na.rm=TRUE),pt.size = 1) + scale_color_viridis_c() 
  #FeaturePlot(brain,x,max.cutoff = 0.08,min.cutoff = 0.02) + scale_color_viridis_c(limits=c(0.02,0.08)) 
  })


```






```{r,fig.width=8,fig.height=4}
brain.merged <- RenameIdents(brain.merged,'0'='non_oligo','1'='oligo','2'='oligo')
brain.merged$cell_type <- brain.merged@active.ident

GFP_colors        <- RColorBrewer::brewer.pal(n = 9,name='Set1')[c(4,3)]
names(GFP_colors) <- c("GFP-","GFP+")

p1 <- DimPlot(object = brain.merged, group.by='Age',label = TRUE,reduction = 'umap',pt.size=0.1) + NoLegend()
p2 <- DimPlot(object = brain.merged, label = TRUE,reduction = 'umap',pt.size=0.1) + NoLegend()
p3 <- DimPlot(object = brain.merged, group.by='GFP',label = TRUE,reduction = 'umap',pt.size=0.1) + scale_color_manual(values = GFP_colors) + theme(legend.position = 'bottom')

p1
p2
p3

```

```{r find_markers_peaks}
brain.merged<- NormalizeData(brain.merged,normalization.method = 'LogNormalize',scale.factor=10000)
markers <- FindAllMarkers(brain.merged,min.pct = 0.02,logfc.threshold = 0.1,slot = 'data')

markers$closest_gene <- ClosestFeature(regions = StringToGRanges(markers$gene ), annotation = genebodyandpromoter.coords.flat)$name
#View(markers)

markers.top <- markers %>% dplyr::filter(avg_logFC > 0) %>% group_by(cluster) %>% top_n(n = 50,wt = avg_logFC)
markers.negative <- markers %>% dplyr::filter(avg_logFC < 0) %>% group_by(cluster) %>% top_n(n = 50,wt = -avg_logFC)

saveRDS(object = brain.merged,      file = paste0(params$out_prefix,params$antibody,"/clustering/01.clustering.Rds"))
write.csv2(  x = markers.top,       file = paste0(params$out_prefix,params$antibody,"/clustering/peaks_markers_top.csv"))
```



```{r export_bw_for_inspection}
# Export bw to inspect cluster 7 merged profile

dir.create(paste0(params$out_prefix,params$antibody,"/clustering/bigwig/clusters_all/"),recursive = TRUE)

samples <- unlist(lapply(config$samples,function(x){x$Antibody}))
samples <- samples[samples == params$antibody]


fragments.path     <- paste0(params$out_prefix,params$antibody,'/fragments.tsv.gz')
fragments.grange   <- rtracklayer::import(con = fragments.path,format = 'bed')

chrom.sizes <- getChromInfoFromUCSC(genome = config$general$Version)
# chrom.sizes <- chrom.sizes[1:21,]


lapply(levels(brain.merged@active.ident),function(x){
  exportBW(object = brain.merged,
           cluster = x,
           fragments = fragments.grange,
           path =  paste0(params$out_prefix,params$antibody,"/clustering/bigwig/cluster_",x,".bw"),
           chrom.sizes = chrom.sizes)
})
```

# Export marker bed file 

# Here, the marker bed file is made of peaks
```{r export_bed}
clusters_order = levels(brain.merged@active.ident)

# Get top markers
top.markers <- markers %>% group_by(cluster) %>% dplyr::filter(avg_logFC > 0) %>% top_n(200, wt=avg_logFC)

# Reorder markers
top.markers$cluster <- factor(as.character(top.markers$cluster),levels=clusters_order[1:sum(table(top.markers$cluster) > 0)])

top.markers         <- as.data.frame(top.markers)
top.markers         <- top.markers[order(top.markers$cluster),]


lapply(levels(top.markers$cluster),function(x){
  top.markers.x <- top.markers[top.markers$cluster == x,]
  top.markers.x <- sort(StringToGRanges(top.markers.x$gene))
  rtracklayer::export.bed(object = top.markers.x,con = paste0(params$out_prefix,params$antibody,"/clustering/markers_bed/markers_cluster_",x,".bed"))
})
```


```{r find_markers_bins}
assay = paste0('bins_',params$window)
DefaultAssay(brain.merged) <- assay

brain.merged<- NormalizeData(brain.merged,normalization.method = 'LogNormalize',scale.factor=10000)
markers <- FindAllMarkers(brain.merged,min.pct = 0.02,logfc.threshold = 0.1,slot = 'data')

markers$closest_gene <- ClosestFeature(regions = StringToGRanges(markers$gene ), annotation = genebodyandpromoter.coords.flat)$name
#View(markers)

markers.top <- markers %>% dplyr::filter(avg_logFC > 0) %>% group_by(cluster) %>% top_n(n = 50,wt = avg_logFC)
markers.negative <- markers %>% dplyr::filter(avg_logFC < 0) %>% group_by(cluster) %>% top_n(n = 50,wt = -avg_logFC)

write.csv2(  x = markers,           file = paste0(params$out_prefix,params$antibody,"/clustering/markers.csv"))
write.csv2(  x = markers.top,       file = paste0(params$out_prefix,params$antibody,"/clustering/markers_top.csv"))
write.csv2(  x = markers.negative,  file = paste0(params$out_prefix,params$antibody,"/clustering/markers_negative.csv"))

```

```{r do_heatmap}

DoHeatmapMB <- function(object, markers,fraction = 0.2,slot = "data",assay, clusterColors){
  
  object <- object[,sample(colnames(object),length(colnames(object)) * fraction)]
  
  row_annotation.df           <- data.frame(markers=markers$cluster)
  rownames(row_annotation.df) <- markers$gene
  col_annotation.df           <- data.frame(clusters=Idents(object))
  col_annotation.df$sample    <- object$sample
  col_annotation.df           <- col_annotation.df[order(col_annotation.df$clusters,col_annotation.df$sample),]
  
  heatmap.mat <- GetAssayData(object = object, slot,assay = assay)
  heatmap.mat <- heatmap.mat[rownames(row_annotation.df),rownames(col_annotation.df)]
  
  print(dim(heatmap.mat))
  
  pheatmap::pheatmap(heatmap.mat,
                     cluster_cols = FALSE, 
                     cluster_rows = FALSE,
                     annotation_row = row_annotation.df,
                     annotation_col = col_annotation.df,
                     color = viridis::viridis(256),
                     show_rownames = FALSE,
                     show_colnames = FALSE,
                     labels_col = "",labels_row = "",
                     annotation_colors = clusterColors)
}

ncells        <- dim(brain.merged)[2]
cells_to_plot <- colnames(brain.merged)[sample(1:ncells,ncells * 0.4)]
cells_to_plot <- tibble::rownames_to_column(brain.merged[,cells_to_plot]@meta.data) %>% arrange(seurat_clusters,sample) %>% pull(rowname)
clusters_order <- levels(brain.merged@active.ident)

# Get top markers
top.markers <- markers %>% group_by(cluster) %>% dplyr::filter(avg_logFC > 0) %>% top_n(100, wt=p_val)
top.markers <- top.markers[which(!top.markers$gene %in% names(table(top.markers$gene)[table(top.markers$gene) > 1])),] # remove non-unique

# Reorder markers
top.markers$cluster <- factor(as.character(top.markers$cluster),levels=clusters_order)
top.markers         <- top.markers[order(top.markers$cluster),]

# Reorder cells
Idents(brain.merged) <- factor(as.character(Idents(brain.merged)),levels=clusters_order)

# Create list of cluster colors
clusterColors <- rep(list(scales::hue_pal()(length(levels(brain.merged@active.ident)))),2)
names(clusterColors) <- c("markers","clusters")
  
names(clusterColors[[1]]) <- levels(brain.merged@active.ident)
names(clusterColors[[2]]) <- levels(brain.merged@active.ident)


png(filename = paste0(params$out_prefix,params$antibody,"/clustering/bins_heatmap.png"),width=1000,height=1000)
DoHeatmapMB(brain.merged,
            markers = top.markers,
            clusterColors = clusterColors,
            slot = 'data',
            assay= assay)
dev.off()

DoHeatmapMB(brain.merged,
            markers = top.markers,
            clusterColors = clusterColors,
            slot = 'data',
            assay= assay)


```


```{r}
cluster.annotations           <- data.frame(cluster=brain.merged@active.ident,
                                            barcode=names(brain.merged@active.ident))

colnames(cluster.annotations) <- paste0("#",colnames(cluster.annotations))

write.csv(x = cluster.annotations, file=paste0(params$out_prefix,params$antibody,'/clustering/bam_per_cluster/cluster_barcode_table.csv'),row.names = FALSE,quote = FALSE,)

```

