---
title: "R Notebook"
output:
  html_document:
    df_print: paged
params:
  antibody: 'Rad21'
  out_prefix: "~/mount/CT/git_test/results/" #'results/'
  samples:
    'Rad21_N1'
  window: 25000
---


```{r}
suppressMessages({
  library(Seurat)
  library(gridExtra)
  library(dplyr)
  library(Signac)
  library(EnsDb.Mmusculus.v79)
  library(ggplot2)
  library(BSgenome.Mmusculus.UCSC.mm10)
})

set.seed(100)
```



# Load the data from precious clustering
```{r,fig.width=12,fig.height=4}

brain            <- readRDS(paste0(params$out_prefix,params$antibody,"/clustering/01.clustering.Rds"))
brain.H3K27ac    <- readRDS(paste0(params$out_prefix,"H3K27ac","/clustering/01.clustering.Rds"))

p1 <- DimPlot(brain.H3K27ac,pt.size = 0.1,label=TRUE) + NoLegend() + ggtitle("H3K27ac")
p2 <- DimPlot(brain,pt.size = 0.1,label=TRUE) + NoLegend() + ggtitle("Olig2")
p1+p2
```

```{r}
assay <- paste0('bins_',params$window)

fragments.H3K27ac <- paste0(params$out_prefix,"merged/H3K27ac/fragments.tsv.gz")
bin.matrix <- GenomeBinMatrix(fragments = fragments.H3K27ac,
                              genome = seqlengths(BSgenome.Mmusculus.UCSC.mm10),
                              cells = colnames(brain.H3K27ac),
                              binsize =  params$window)


brain.H3K27ac[[assay]] <- CreateAssayObject(counts = bin.matrix)
```



```{r}
DefaultAssay(brain)         <- assay
DefaultAssay(brain.H3K27ac) <- assay

brain.H3K27ac$cell_type <- brain.H3K27ac@active.ident
brain$cell_type         <- brain@active.ident

```


```{r}
rm(anchors)
rm(integrated)

peaks.use <- intersect(rownames(brain.H3K27ac[Matrix::rowSums(brain.H3K27ac[[assay]]@counts)> 5,]), 
                       rownames(brain[Matrix::rowSums(brain[[assay]]@counts)> 5,]))

anchors <- FindIntegrationAnchors(
  object.list = list(brain.H3K27ac,brain),
  anchor.features = peaks.use,
  assay = c(assay,assay),
  k.filter = NA)

integrated <- IntegrateData(
  anchorset = anchors,
  preserve.order = TRUE)

integrated <- RunSVD(
  object = integrated,
  n = 50,
  reduction.name = 'integratedLSI'
)

integrated <- RunUMAP(
  object = integrated,
  dims = 2:30,
  reduction = 'integratedLSI')


p3 <- DimPlot(integrated, group.by = 'orig.ident', pt.size = 0.2) + ggplot2::ggtitle("Integrated")

p4 <- DimPlot(integrated[,integrated$antibody == "H3K27ac"], pt.size = 0.2, label=TRUE,group.by='cell_type') + ggplot2::ggtitle("H3K27ac") + NoLegend()
p5 <- DimPlot(integrated[,integrated$antibody == "Rad21"], pt.size = 0.2, label=TRUE,group.by='cell_type') + ggplot2::ggtitle("Olig2") + NoLegend() 
  

p3
p4
p5
p4+ p5
```



```{r}
brain.new <-integrated[,integrated$antibody == "Rad21"]

brain.new <- FindNeighbors(
  object = brain.new,
  reduction = 'integratedLSI',
  dims = 2:20
)
brain.new <- FindClusters(
  object = brain.new,
  algorithm = 3,
  resolution = 0.2,
  verbose = FALSE
)


DimPlot(brain.new,label = TRUE)
FeaturePlot(brain.new,'logUMI',max.cutoff = 2.5) + scale_color_viridis_c()
```

```{r}
samples <- gsub(" ","",unlist(strsplit(params$samples,",")))
fragments <- paste0(params$out_prefix,samples,'merged/Rad21/fragments.tsv.gz')

fragments.ls <-lapply(fragments,function(x){
  fragments <- rtracklayer::import(x,format = "bed")  
})

fragments <- Reduce(function(x,y) c(x,y), fragments.ls)
fragments <- sort(fragments)

chrom.sizes <- read.table(url('http://hgdownload.cse.ucsc.edu/goldenPath/mm10/bigZips/mm10.chrom.sizes'),sep="\t",stringsAsFactors = FALSE)
chrom.sizes <- chrom.sizes[1:21,]


exportBW <- function(object,cluster,fragments){

  if(class(object) == "Seurat"){
    cells <- rownames(object@meta.data[object@active.ident == cluster,])
  }
  
   new_read <- GRanges(seqnames = chrom.sizes[,1], 
          ranges =IRanges(start = as.numeric(chrom.sizes[,2]),
                          width=1),
          name = rep("in_silico_extra_read",dim(chrom.sizes)[1]),
          score = rep(0,dim(chrom.sizes)[1])
          )
  
  fragments.x <- fragments$name %in% cells
  fragments.x <- fragments[fragments.x]
  fragments.x <- c(fragments.x,new_read)
  
  
  coverage.x <- coverage(fragments.x)
  coverage.x <- coverage.x / length(fragments.x)/1e3
  rtracklayer::export.bw(object = coverage.x, con = paste0(params$out_prefix,params$antibody,'/integration/bigwig/cluster_',cluster,'.bw'))
}

lapply(levels(brain.new@active.ident),function(x){
  exportBW(brain.new,x,fragments)
})

saveRDS(object = integrated,file = paste0(params$out_prefix,params$antibody,'/integration/integrated.Rds'))

```

