samples:
  H3K4me3_N1: 
    cellranger_out: /data/proj/GCB_MB/CT/CT_20_005
    clustering_params: 
      min_reads_log10: 4.0
      max_reads_log10: 5.5
      min_peaks_ratio: 0.5
      max_peaks_ratio: 0.98
    GFP: GFP+
    Age: P25
    Antibody: H3K4me3
  H3K4me3_N2: 
    cellranger_out: /data/proj/GCB_MB/CT/CT_20_009
    clustering_params: 
      min_reads_log10: 3.7
      max_reads_log10: 5.5
      min_peaks_ratio: 0.5
      max_peaks_ratio: 0.98
    GFP: GFP+
    Age: P25
    Antibody: H3K4me3
  H3K4me3_N3: 
    cellranger_out: /data/proj/GCB_MB/CT/CT_20_MB01b/CT_20_MB01
    clustering_params: 
      min_reads_log10: 2.3 
      max_reads_log10: 5
      min_peaks_ratio: 0.5
      max_peaks_ratio: 0.98
    GFP: GFP+
    Age: P15
    Antibody: H3K4me3
  H3K4me3_N4: 
    cellranger_out: /data/proj/GCB_MB/CT/CT_20_MB02b
    clustering_params: 
      min_reads_log10: 2.5
      max_reads_log10: 5.0
      min_peaks_ratio: 0.5
      max_peaks_ratio: 0.98
    GFP: GFP-
    Age: P15
    Antibody: H3K4me3
        
  
  H3K27me3_N1: 
    cellranger_out: /data/proj/GCB_MB/CT/CT_19_003
    clustering_params: 
      min_reads_log10: 3.2
      max_reads_log10: 6.0
      min_peaks_ratio: 0.2
      max_peaks_ratio: 0.75
    GFP: GFP+
    Age: P25
    Antibody: H3K27me3
  H3K27me3_N2: 
    cellranger_out: /data/proj/GCB_MB/CT/CT_20_006
    clustering_params: 
      min_reads_log10: 3.5
      max_reads_log10: 6.0
      min_peaks_ratio: 0.2
      max_peaks_ratio: 0.75
    GFP: GFP+
    Age: P25
    Antibody: H3K27me3
  H3K27me3_N3: 
    cellranger_out: /data/proj/GCB_MB/CT/CT_20_MB03
    clustering_params: 
      min_reads_log10: 2.3
      max_reads_log10: 4.5
      min_peaks_ratio: 0.05
      max_peaks_ratio: 0.75
    GFP: GFP+
    Age: P15
    Antibody: H3K27me3
  H3K27me3_N4: 
    cellranger_out: /data/proj/GCB_MB/CT/CT_20_MB04
    clustering_params: 
      min_reads_log10: 2.5
      max_reads_log10: 5.0
      min_peaks_ratio: 0.05
      max_peaks_ratio: 0.75
    GFP: GFP-
    Age: P15
    Antibody: H3K27me3

  H3K27ac_N1:
    cellranger_out: /data/proj/GCB_MB/CT/CT_19_001
    clustering_params:
      min_reads_log10: 3.5
      max_reads_log10: 5.5
      min_peaks_ratio: 0.15
      max_peaks_ratio: 0.75
    GFP: GFP+
    Age: P25
    Antibody: H3K27ac
  H3K27ac_N2:
    cellranger_out: /data/proj/GCB_MB/CT/CT_19_002
    clustering_params:
      min_reads_log10: 3.0
      max_reads_log10: 6.0
      min_peaks_ratio: 0.25
      max_peaks_ratio: 0.75
    GFP: GFP+
    Age: P25
    Antibody: H3K27ac

  H3K36me3_N1:
    cellranger_out: /data/proj/GCB_MB/CT/CT_20_001
    clustering_params:
      min_reads_log10: 3.5
      max_reads_log10: 5.5
      min_peaks_ratio: 0.15
      max_peaks_ratio: 0.75
    GFP: GFP+
    Age: P25
    Antibody: H3K36me3
  H3K36me3_N2:
    cellranger_out: /data/proj/GCB_MB/CT/CT_20_008
    clustering_params:
      min_reads_log10: 3.5
      max_reads_log10: 5.5
      min_peaks_ratio: 0.15
      max_peaks_ratio: 0.75
    GFP: GFP+
    Age: P25
    Antibody: H3K36me3

  Olig2_N1:
    cellranger_out: /data/proj/GCB_MB/CT/CT_20_003
    clustering_params:
      min_reads_log10: 3.0
      max_reads_log10: 6
      min_peaks_ratio: 0.25
      max_peaks_ratio: 0.98
    GFP: GFP+
    Age: P25
    Antibody: Olig2
  Olig2_N2:
    cellranger_out: /data/proj/GCB_MB/CT/CT_20_010
    clustering_params:
      min_reads_log10: 3.0
      max_reads_log10: 6
      min_peaks_ratio: 0.5
      max_peaks_ratio: 0.98
    GFP: GFP+
    Age: P25
    Antibody: Olig2

  Rad21_N1:
    cellranger_out: /data/proj/GCB_MB/CT/CT_20_007
    clustering_params:
      min_reads_log10: 3.7
      max_reads_log10: 5.8
      min_peaks_ratio: 0.5
      max_peaks_ratio: 0.98
    GFP: GFP+
    Age: P25
    Antibody: Rad21

general:
  clustering_window: [1000,10000,5000,25000,50000,100000]
  conda_env: CT_snakemake

RNA_seq:
  Sox10_RNA:
    # Output from cellranger
    replicate1:    /data/proj/GCB_MB/CT/RNA_seq/10X_20_033b/
    replicate2:    /data/proj/GCB_MB/CT/RNA_seq/10X_20_034b/
  Sten_RNA:
    # Loom file from Linnarsson web
    loom_source:  https://storage.googleapis.com/linnarsson-lab-loom/l5_all.loom
    loom_file:     results/Sten_RNA/l5_all.loom
  Marques_RNA:
    url: https://ftp.ncbi.nlm.nih.gov/geo/series/GSE75nnn/GSE75330/suppl/GSE75330_Marques_et_al_mol_counts2.tab.gz

ATAC_seq:
  P50:
    url:
      matrix_h5_url:        https://cf.10xgenomics.com/samples/cell-atac/1.2.0/atac_v1_adult_brain_fresh_5k/atac_v1_adult_brain_fresh_5k_filtered_peak_bc_matrix.h5
      matrix_url:           https://cf.10xgenomics.com/samples/cell-atac/1.2.0/atac_v1_adult_brain_fresh_5k/atac_v1_adult_brain_fresh_5k_filtered_peak_bc_matrix.tar.gz
      fragments_url:        https://cf.10xgenomics.com/samples/cell-atac/1.2.0/atac_v1_adult_brain_fresh_5k/atac_v1_adult_brain_fresh_5k_fragments.tsv.gz
      fragments_index_url:  https://cf.10xgenomics.com/samples/cell-atac/1.2.0/atac_v1_adult_brain_fresh_5k/atac_v1_adult_brain_fresh_5k_fragments.tsv.gz.tbi
      metadata_url:         https://cf.10xgenomics.com/samples/cell-atac/1.2.0/atac_v1_adult_brain_fresh_5k/atac_v1_adult_brain_fresh_5k_singlecell.csv
      bam_url:              https://cg.10xgenomics.com/samples/cell-atac/1.2.0/atac_v1_adult_brain_fresh_5k/atac_v1_adult_brain_fresh_5k_possorted_bam.bam
      bam_index_url:        https://cf.10xgenomics.com/samples/cell-atac/1.2.0/atac_v1_adult_brain_fresh_5k/atac_v1_adult_brain_fresh_5k_possorted_bam.bam.bai

db:
  genome_fa: "/data/proj/GCB_MB/reference/fasta_masked/mm10/mm10.fa.masked"


# pip install https://github.com/mirnylab/cooltools/archive/master.zip
# pip install coolpuppy
# pip install hic2cool

