samples:
  H3K4me3_N1: 
    cellranger_out: /data/proj/GCB_MB/CT/CT_20_005
    clustering_params: 
      min_reads_log10: 4.0
      max_reads_log10: 5.5
      min_peaks_ratio: 0.5
      max_peaks_ratio: 0.98
    GFP: GFP+
    Age: P25
    Antibody: H3K4me3
    window: 5000
  H3K4me3_N2: 
    cellranger_out: /data/proj/GCB_MB/CT/CT_20_009
    clustering_params: 
      min_reads_log10: 3.7
      max_reads_log10: 5.5
      min_peaks_ratio: 0.5
      max_peaks_ratio: 0.98
    GFP: GFP+
    Age: P25
    Antibody: H3K4me3
    window: 5000
  H3K4me3_N3: 
    cellranger_out: /data/proj/GCB_MB/CT/CT_20_MB01b/CT_20_MB01
    clustering_params: 
      min_reads_log10: 2.3 
      max_reads_log10: 5
      min_peaks_ratio: 0.5
      max_peaks_ratio: 0.98
    GFP: GFP+
    Age: P15
    Antibody: H3K4me3
    window: 5000
  H3K4me3_N4: 
    cellranger_out: /data/proj/GCB_MB/CT/CT_20_MB02b
    clustering_params: 
      min_reads_log10: 2.5
      max_reads_log10: 5.0
      min_peaks_ratio: 0.5
      max_peaks_ratio: 0.98
    GFP: GFP-
    Age: P15
    Antibody: H3K4me3
    window: 5000
  
  H3K27me3_N1: 
    cellranger_out: /data/proj/GCB_MB/CT/CT_19_003
    clustering_params: 
      min_reads_log10: 3.2
      max_reads_log10: 6.0
      min_peaks_ratio: 0.2
      max_peaks_ratio: 0.75
    GFP: GFP+
    Age: P25
    Antibody: H3K27me3
    window: 5000
  H3K27me3_N2: 
    cellranger_out: /data/proj/GCB_MB/CT/CT_20_006
    clustering_params: 
      min_reads_log10: 3.5
      max_reads_log10: 6.0
      min_peaks_ratio: 0.2
      max_peaks_ratio: 0.75
    GFP: GFP+
    Age: P25
    Antibody: H3K27me3
    window: 5000
  H3K27me3_N3: 
    cellranger_out: /data/proj/GCB_MB/CT/CT_20_MB03
    clustering_params: 
      min_reads_log10: 2.3
      max_reads_log10: 4.5
      min_peaks_ratio: 0.05
      max_peaks_ratio: 0.75
    GFP: GFP+
    Age: P15
    Antibody: H3K27me3
    window: 5000
  H3K27me3_N4: 
    cellranger_out: /data/proj/GCB_MB/CT/CT_20_MB04
    clustering_params: 
      min_reads_log10: 2.5
      max_reads_log10: 5.0
      min_peaks_ratio: 0.05
      max_peaks_ratio: 0.75
    GFP: GFP-
    Age: P15
    Antibody: H3K27me3
    window: 5000
  
  H3K27me3_cell_lines_1: 
    cellranger_out: /data/proj/GCB_MB/CT/CT_20_MB006
    clustering_params: 
      min_reads_log10: 3.5
      max_reads_log10: 5.5
      min_peaks_ratio: 0.05
      max_peaks_ratio: 0.75
    GFP: GFP-
    Age: P15
    Antibody: H3K27me3_cell_lines
    window: 5000
  H3K27me3_cell_lines_2: 
    cellranger_out: /data/proj/GCB_MB/CT/CT_20_MB007
    clustering_params: 
      min_reads_log10: 3.5
      max_reads_log10: 5.5
      min_peaks_ratio: 0.05
      max_peaks_ratio: 0.75
    GFP: GFP-
    Age: P15
    Antibody: H3K27me3_cell_lines
    window: 5000

  H3K27ac_N1:
    cellranger_out: /data/proj/GCB_MB/CT/CT_19_001
    clustering_params:
      min_reads_log10: 3.5
      max_reads_log10: 5.5
      min_peaks_ratio: 0.15
      max_peaks_ratio: 0.75
    GFP: GFP+
    Age: P25
    Antibody: H3K27ac
    window: 5000
  H3K27ac_N2:
    cellranger_out: /data/proj/GCB_MB/CT/CT_19_002
    clustering_params:
      min_reads_log10: 3.0
      max_reads_log10: 6.0
      min_peaks_ratio: 0.25
      max_peaks_ratio: 0.75
    GFP: GFP+
    Age: P25
    Antibody: H3K27ac
    window: 5000

  H3K36me3_N1:
    cellranger_out: /data/proj/GCB_MB/CT/CT_20_001
    clustering_params:
      min_reads_log10: 3.5
      max_reads_log10: 5.5
      min_peaks_ratio: 0.15
      max_peaks_ratio: 0.75
    GFP: GFP+
    Age: P25
    Antibody: H3K36me3
    window: 50000
  H3K36me3_N2:
    cellranger_out: /data/proj/GCB_MB/CT/CT_20_008
    clustering_params:
      min_reads_log10: 3.5
      max_reads_log10: 5.5
      min_peaks_ratio: 0.15
      max_peaks_ratio: 0.75
    GFP: GFP+
    Age: P25
    Antibody: H3K36me3
    window: 50000

  Olig2_N1:
    cellranger_out: /data/proj/GCB_MB/CT/CT_20_003
    clustering_params:
      min_reads_log10: 3.0
      max_reads_log10: 6
      min_peaks_ratio: 0.25
      max_peaks_ratio: 0.98
    GFP: GFP+
    Age: P25
    Antibody: Olig2
    window: 5000
  Olig2_N2:
    cellranger_out: /data/proj/GCB_MB/CT/CT_20_010
    clustering_params:
      min_reads_log10: 3.0
      max_reads_log10: 6
      min_peaks_ratio: 0.5
      max_peaks_ratio: 0.98
    GFP: GFP+
    Age: P25
    Antibody: Olig2
    window: 5000

  Rad21_N1:
    cellranger_out: /data/proj/GCB_MB/CT/CT_20_007
    clustering_params:
      min_reads_log10: 3.7
      max_reads_log10: 5.8
      min_peaks_ratio: 0.5
      max_peaks_ratio: 0.98
    GFP: GFP+
    Age: P25
    Antibody: Rad21
    window: 5000

general:
  clustering_window: [1000,10000,5000,25000,50000,100000]
  conda_env: CT_snakemake
  tmpdir: /data/proj/GCB_MB/tmp

RNA_seq:
  Sox10_RNA:
    # Output from cellranger
    replicate1:    /data/proj/GCB_MB/CT/RNA_seq/10X_20_033b/
    replicate2:    /data/proj/GCB_MB/CT/RNA_seq/10X_20_034b/
  Sten_RNA:
    # Loom file from Linnarsson web
    loom_source:  https://storage.googleapis.com/linnarsson-lab-loom/l5_all.loom
    loom_file:     results/Sten_RNA/l5_all.loom
  Marques_RNA:
    url: https://ftp.ncbi.nlm.nih.gov/geo/series/GSE75nnn/GSE75330/suppl/GSE75330_Marques_et_al_mol_counts2.tab.gz

ATAC_seq:
  P50:
    url:
      matrix_h5:        https://cf.10xgenomics.com/samples/cell-atac/1.2.0/atac_v1_adult_brain_fresh_5k/atac_v1_adult_brain_fresh_5k_filtered_peak_bc_matrix.h5
      matrix:           https://cf.10xgenomics.com/samples/cell-atac/1.2.0/atac_v1_adult_brain_fresh_5k/atac_v1_adult_brain_fresh_5k_filtered_peak_bc_matrix.tar.gz
      fragments:        https://cf.10xgenomics.com/samples/cell-atac/1.2.0/atac_v1_adult_brain_fresh_5k/atac_v1_adult_brain_fresh_5k_fragments.tsv.gz
      fragments_index:  https://cf.10xgenomics.com/samples/cell-atac/1.2.0/atac_v1_adult_brain_fresh_5k/atac_v1_adult_brain_fresh_5k_fragments.tsv.gz.tbi
      metadata:         https://cf.10xgenomics.com/samples/cell-atac/1.2.0/atac_v1_adult_brain_fresh_5k/atac_v1_adult_brain_fresh_5k_singlecell.csv
      bam:              https://cg.10xgenomics.com/samples/cell-atac/1.2.0/atac_v1_adult_brain_fresh_5k/atac_v1_adult_brain_fresh_5k_possorted_bam.bam
      bam_index:        https://cf.10xgenomics.com/samples/cell-atac/1.2.0/atac_v1_adult_brain_fresh_5k/atac_v1_adult_brain_fresh_5k_possorted_bam.bam.bai

grosselin:
  scChIP:
     SRR7536860:
       SRA: SRR7536860
       count_table: ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3290nnn/GSM3290889/suppl/GSM3290889_CountTable_HBCx-95_scChIP_H3K27me3_hg38.txt.gz
     SRR7536861:
       SRA: SRR7536861
       count_table: ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3290nnn/GSM3290890/suppl/GSM3290890_CountTable_HBCx-95-CapaR_scChIP_H3K27me3_hg38.txt.gz
     SRR7536862:
       SRA: SRR7536862
       count_table: ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3290nnn/GSM3290891/suppl/GSM3290891_CountTable_HBCx-22_scChIP_H3K27me3_hg38.txt.gz

#    - SRR7536863
#    - SRR7536864
#    - SRR7536865
#    - SRR7536866
#    - SRR7536867
#  test:
#    - SRR7536860

  bowtie2_index: 
    hg38: /data/ref/bowtie2/GRCh38
    mm10: /data/proj/GCB_MB/reference/bowtie2_index/mm10/mm10
  conda_env: CT_snakemake
  
kaya-okur:
  samples: 
    - GSM3536515_K562_K27me3_Rep1
    - GSM3536515_K562_K27me3_Rep2
    - GSM3536517_K562_K4me2_Rep1
    - GSM3536517_K562_K4me2_Rep2
    - GSM3536500_H1_K4me2_Rep1
    - GSM3536500_H1_K4me2_Rep2
    - K562_H3K27me3_iCell8
    - K562_H3K4me2_iCell8
    - H1_H3K27me3_iCell8
  
bonev:
  samples:
    CN_H3K27me3: ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE96nnn/GSE96107/suppl/GSE96107_CN_H3K27me3.bw
    CN_H3K4me3: ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE96nnn/GSE96107/suppl/GSE96107_CN_H3K4me3.bw

matsuda:
  samples:
    microglia_H3K4me3: ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM2800nnn/GSM2800522/suppl/GSM2800522_Microglia_H3K4me3_ChIP-seq.bw
    microglia_H3K27me3: ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM2800nnn/GSM2800523/suppl/GSM2800523_Microglia_H3K27me3_ChIP-seq.bw

zhao:
  samples:
    OPCs_H3K4me3: ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3214nnn/GSM3214323/suppl/GSM3214323_mouse_OPC_H3K4me3chIP-seq_control.wig.gz

mESC:
  samples:
    rep1: https://www.encodeproject.org/files/ENCFF359LIR/@@download/ENCFF359LIR.bam
    rep2: https://www.encodeproject.org/files/ENCFF129XSB/@@download/ENCFF129XSB.bam
  peaks: https://www.encodeproject.org/files/ENCFF105NKG/@@download/ENCFF105NKG.bed.gz
    
3T3:
  samples:
    rep1: SRR9889940
    rep2: SRR9889941

CR_GCB:
    Oli-neu: 
      bigwig: "/data/proj/GCB_MB/cut_tag_GCB_lab/H3K27me3_olineu/P13556_1015_dedup.bw"
      bam: /data/proj/GCB_MB/cut_tag_GCB_lab/H3K27me3_olineu/P13556_1015_sorted.bam
    OPC: 
      bigwig: "/data/proj/GCB_MB/cut_tag_GCB_lab/H3K27me3_OPCs/P13556_1026_dedup.bw"

db:
  genome_fa: "/data/proj/GCB_MB/reference/fasta_masked/mm10/mm10.fa.masked"
  genes_gtf: "/data/ref/cellranger-atac/refdata-cellranger-atac-mm10-1.2.0/genes/genes.gtf"


# pip install https://github.com/mirnylab/cooltools/archive/master.zip
# pip install coolpuppy
# pip install hic2cool

