---
title: "R Notebook"
output: html_notebook
params:
  out_prefix: '~/mount/CT/git_test/results/'  
---

```{r}
library(Seurat)
library(ggplot2)
library(dplyr)
library(gridExtra)
library(ggridges)
library(Signac)
library(ggthemes)
library(pheatmap)
library(GenomicRanges)
library(EnsDb.Mmusculus.v79)

set.seed(2020)

# order clusters
clusters_order <- c("Astrocytes","VLMC","mOL","Neurons_1","Neurons_2","Neurons_3","OEC","OPC","Microglia")

# Colors definition - consistent accross the paper
CTcolors        <- scales::hue_pal()(9)
names(CTcolors) <- clusters_order

```

```{r}
dir.create(paste0(params$out_prefix,'Figures/figure2_src'))
```


# H3K4me3 Sox10

```{r echo=FALSE}
fetchFragmentsByRegion <- function(fragments, region, fraction, object ) { 
    
    if(length(region) > 1){
        stop("Only one region can be used")
    }

    if(class(region)[1] == "GRanges"){
        seqlevelsStyle(region) <- "UCSC"
        chr    = as.character(seqnames(region))
        from  = as.numeric(start(region))
        to    = as.numeric(end(region))
    }
    
    if(class(region)[1] == "character"){
        region <- strsplit(region,":|-")[[1]]
        
        chr    = as.character(region[1])
        from  = as.numeric(region[2])
        to    = as.numeric(region[3])
    }

    
    # Extract fragments overalpping the region
    fragments.interesting <- fragments[seqnames(fragments) == chr]
    fragments.interesting <- fragments.interesting[start(fragments.interesting) > from]
    fragments.interesting <- fragments.interesting[end(fragments.interesting) < to]
    
    return(fragments.interesting)

}

filterCells <- function(object,fragments,fraction){
     # Make fragments per cell table
    fragments.summary <- sort(table(c(fragments$name,colnames(object))),decreasing = TRUE) - 1
    
    # Split cells by cluster - return fraction of cells per cluster
    fragments.summary.ls <-  lapply(levels(object@active.ident),function(x){
      object.x <- object[,object@active.ident == x]
      barcodes <- colnames(object.x)
      fragments.summary.x <- fragments.summary[names(fragments.summary) %in% barcodes]
      fragments.summary.x <- sort(fragments.summary.x,decreasing = TRUE)
      head(x = fragments.summary.x, n = dim(object.x)[2] * fraction)
    })
    
    # unlist and merge cella names
    cells <- unlist(lapply(fragments.summary.ls,names))
    return(cells)
}


fragmentsToMatrix <- function(fragments,window){
    bins <- tile(range(fragments),width=window)[[1]]
    
    fragments.ls <- split(fragments,as.factor(fragments$name))
    seqlevels(bins,pruning.mode = "coarse") <- names(coverage(fragments.ls[[1]]))

    fragments.ls.coverage <- lapply(fragments.ls,function(x){
        x <- coverage(x)
        x.bins <- binnedAverage(bins = bins,numvar = x, "coverage")
        as.numeric(x.bins$coverage)
    })
    
    fragments.matrix <- t(do.call("rbind",fragments.ls.coverage))
    rownames(fragments.matrix) <- start(bins)
    
    return(fragments.matrix)
}


plotHeatmapBW <- function(object,
                       fragmentsGrange,
                       interestingRegion,
                       window = 5000,
                       annotFilter,
                       fraction = 0.1,
                       clusters_order = NULL,
                       cells = NULL,...
                       ) {
  
if(is.null(clusters_order)){clusters_order  <- levels(object@active.ident)}
if(is.null(cells)){cells.to.plot            <- sample(colnames(object),fraction * dim(object)[2])}

fragments.interesting <- fragmentsGrange  


fragments.interesting.matrix <- fragmentsToMatrix(fragments    = fragments.interesting,
                                                  window       = window)


fragments.interesting.matrix <- fragments.interesting.matrix[,colnames(fragments.interesting.matrix) %in% cells]


dummy.mat <- matrix(data = 0, nrow = dim(fragments.interesting.matrix)[1],ncol = length(cells.to.plot[!cells.to.plot %in% colnames(fragments.interesting.matrix)]))
colnames(dummy.mat) <- cells.to.plot[!cells.to.plot %in% colnames(fragments.interesting.matrix)]
rownames(dummy.mat) <- rownames(fragments.interesting.matrix)

fragments.interesting.matrix <- cbind(fragments.interesting.matrix,dummy.mat)
                                                  
fragments.interesting.matrix.binary <- apply(fragments.interesting.matrix,2,as.logical)
fragments.interesting.matrix.binary <- Matrix::Matrix(apply(fragments.interesting.matrix.binary,2,as.numeric),sparse = TRUE)

rownames(fragments.interesting.matrix) <- as.numeric(rownames(fragments.interesting.matrix))
rownames(fragments.interesting.matrix.binary) <- as.numeric(rownames(fragments.interesting.matrix))


####################################################
round_coordinates = 250000



clusters_annotations <- sample(factor(object@active.ident[colnames(fragments.interesting.matrix.binary)],levels = clusters_order))

annotation_row       <- data.frame(clusters_annotations[order(clusters_annotations)])
colnames(annotation_row) <- "Cluster"

xlabels  <- as.numeric(rownames(fragments.interesting.matrix))
xlabels[xlabels %% round_coordinates != 0] <- ""

p1 <- pheatmap(t(fragments.interesting.matrix.binary)[rownames(annotation_row),],
         cluster_rows=FALSE,
         cluster_cols=FALSE,
         show_rownames=FALSE,
         show_colnames=TRUE,
         labels_col = xlabels,
         annotation_row = annotation_row,
         annotation_legend= TRUE,
         annotation_names_row = FALSE,
         color = colorRampPalette(c("white","black"))(2),
         gaps_row= cumsum(table(annotation_row$Cluster)[clusters_order]),
         border_color = NA,...
         )

return(p1)
}

```


```{r}
brain.H3K4me3 <- readRDS(paste0(params$out_prefix,'H3K4me3',"/clustering/01.clustering.Rds"))


fragments <- paste0(params$out_prefix,'/merged/H3K4me3/fragments.tsv.gz')
fragments <- rtracklayer::import(fragments,format='bed')

interesting_region <- StringToGRanges("chr15:79105302-79183935",sep=c(":","-"))
seqlevelsStyle(interesting_region) <- "NCBI"
window_bin = 250



flt <- AnnotationFilterList(TxBiotypeFilter("protein_coding"),
                            GRangesFilter(interesting_region),
                            logicOp = c("&"))

fragments.interesting <- fetchFragmentsByRegion(fragments = fragments,
                                                region    = interesting_region,
                                                fraction  = fraction,
                                                object    = object)

fragments.interesting <- fragments.interesting[fragments.interesting$name %in% colnames(brain.H3K4me3)]
fraction              <- length(unique(fragments.interesting$name)) / dim(brain.H3K4me3)[2]
cells.to.plot         <- filterCells(object = brain.H3K4me3,
                                     fragments = fragments.interesting,
                                     fraction=fraction)



p <- plotHeatmapBW(object = brain.H3K4me3,
            fragmentsGrange = fragments.interesting,
            cells = cells.to.plot,
            interestingRegion = interesting_region,
            window = window_bin,
            annotFilter = flt,
            fraction = fraction,
            annotation_colors = list('Cluster' = CTcolors))


ensdb <- EnsDb.Mmusculus.v79
p2 <- ggbio::autoplot(ensdb,which=flt,names.expr="gene_name",mode='reduce') + 
   theme_bw() +   
   coord_cartesian(xlim=c(start(interesting_region),end(interesting_region))) + 
   theme(plot.margin = margin(t = 5.5, r = 0, b = 5.5, l = -20,unit="pt"))


png(file = paste0(params$out_prefix,'/Figures/figure2_src/H3K4me3_Sox10_heatmap.png'),width = 2048,height = 2048)
p
dev.off()



setEPS()
postscript(file = paste0(params$out_prefix,'/Figures/figure2_src/Sox10_gene_model.eps'),width = 8,height = 4)
p2
dev.off()
    
```

```{r}
brain.H3K27me3 <- readRDS(paste0(params$out_prefix,'H3K27me3',"/clustering/01.clustering.Rds"))
brain.H3K27me3 <- RenameIdents(brain.H3K27me3,c('Micoglia'='Microglia'))

fragments <- paste0(params$out_prefix,'/merged/H3K27me3/fragments.tsv.gz')
fragments <- rtracklayer::import(fragments,format='bed')

interesting_region <- StringToGRanges("chr15:79105302-79183935",sep=c(":","-"))
seqlevelsStyle(interesting_region) <- "NCBI"
window_bin = 100



flt <- AnnotationFilterList(TxBiotypeFilter("protein_coding"),
                            GRangesFilter(interesting_region),
                            logicOp = c("&"))

fragments.interesting <- fetchFragmentsByRegion(fragments = fragments,
                                                region    = interesting_region,
                                                fraction  = fraction,
                                                object    = object)

fragments.interesting <- fragments.interesting[fragments.interesting$name %in% colnames(brain.H3K27me3)]
fraction              <- length(unique(fragments.interesting$name)) / dim(brain.H3K27me3)[2]
cells.to.plot         <- filterCells(object = brain.H3K27me3,
                                     fragments = fragments.interesting,
                                     fraction=fraction)

p <- plotHeatmapBW(object = brain.H3K27me3,
            fragmentsGrange = fragments.interesting,
            cells = cells.to.plot,
            interestingRegion = interesting_region,
            window = window_bin,
            annotFilter = flt,
            fraction = fraction,
            annotation_colors = list('Cluster' = CTcolors),
            clusters_order = levels(brain.H3K4me3@active.ident)) # To have the order the same as in H3K4me3

print(p)

ensdb <- EnsDb.Mmusculus.v79
p2 <- ggbio::autoplot(ensdb,which=flt,names.expr="gene_name",mode='reduce') + 
   theme_bw() +   
   coord_cartesian(xlim=c(start(interesting_region),end(interesting_region))) + 
   theme(plot.margin = margin(t = 5.5, r = 0, b = 5.5, l = -20,unit="pt"))


png(file = paste0(params$out_prefix,'/Figures/figure2_src/H3K27me3_Sox10_heatmap.png'),width = 2048,height = 2048)
p
dev.off()



setEPS()
postscript(file =paste0(params$out_prefix,'/Figures/figure2_src/Sox10_gene_model.eps'),width = 8,height = 4)
p2
dev.off()
    
```

 # H3K27ac

```{r}
brain.H3K27ac <- readRDS(paste0(params$out_prefix,'H3K27ac',"/clustering/01.clustering.Rds"))

fragments <- paste0(params$out_prefix,'/merged/H3K27ac/fragments.tsv.gz')
fragments <- rtracklayer::import(fragments,format='bed')

interesting_region <- StringToGRanges("chr15:79105302-79183935",sep=c(":","-"))
seqlevelsStyle(interesting_region) <- "NCBI"
window_bin = 100



flt <- AnnotationFilterList(TxBiotypeFilter("protein_coding"),
                            GRangesFilter(interesting_region),
                            logicOp = c("&"))

fragments.interesting <- fetchFragmentsByRegion(fragments = fragments,
                                                region    = interesting_region,
                                                fraction  = fraction,
                                                object    = object)

fragments.interesting <- fragments.interesting[fragments.interesting$name %in% colnames(brain.H3K27ac)]
fraction              <- length(unique(fragments.interesting$name)) / dim(brain.H3K27ac)[2]
cells.to.plot         <- filterCells(object = brain.H3K27ac,
                                     fragments = fragments.interesting,
                                     fraction=fraction)

p <- plotHeatmapBW(object = brain.H3K27ac,
            fragmentsGrange = fragments.interesting,
            cells = cells.to.plot,
            interestingRegion = interesting_region,
            window = window_bin,
            annotFilter = flt,
            fraction = fraction,
            annotation_colors = list('Cluster' = CTcolors),
            clusters_order = levels(brain.H3K4me3@active.ident)) # To have the order the same as in H3K4me3

print(p)

ensdb <- EnsDb.Mmusculus.v79
p2 <- ggbio::autoplot(ensdb,which=flt,names.expr="gene_name",mode='reduce') + 
   theme_bw() +   
   coord_cartesian(xlim=c(start(interesting_region),end(interesting_region))) + 
   theme(plot.margin = margin(t = 5.5, r = 0, b = 5.5, l = -20,unit="pt"))


png(file = paste0(params$out_prefix,'/Figures/figure2_src/H3K27ac_Sox10_heatmap.png'),width = 2048,height = 1024)
p
dev.off()



setEPS()
postscript(file =paste0(params$out_prefix,'/Figures/figure2_src/Sox10_gene_model.eps'),width = 8,height = 4)
p2
dev.off()
    
```

# H3K36me3

```{r}
brain.H3K36me3 <- readRDS(paste0(params$out_prefix,'H3K36me3',"/clustering/01.clustering.Rds"))
brain.H3K36me3 <- RenameIdents(brain.H3K36me3,c("Vascular" = "VLMC"))
brain.H3K36me3 <- brain.H3K36me3[,brain.H3K36me3@active.ident != "Unknown"]

fragments <- paste0(params$out_prefix,'/merged/H3K36me3/fragments.tsv.gz')
fragments <- rtracklayer::import(fragments,format='bed')

interesting_region <- StringToGRanges("chr15:79105302-79183935",sep=c(":","-"))
seqlevelsStyle(interesting_region) <- "NCBI"
window_bin = 100



flt <- AnnotationFilterList(TxBiotypeFilter("protein_coding"),
                            GRangesFilter(interesting_region),
                            logicOp = c("&"))

fragments.interesting <- fetchFragmentsByRegion(fragments = fragments,
                                                region    = interesting_region,
                                                fraction  = fraction,
                                                object    = object)

fragments.interesting <- fragments.interesting[fragments.interesting$name %in% colnames(brain.H3K36me3)]
fraction              <- length(unique(fragments.interesting$name)) / dim(brain.H3K36me3)[2]
cells.to.plot         <- filterCells(object = brain.H3K36me3,
                                     fragments = fragments.interesting,
                                     fraction=fraction)

p <- plotHeatmapBW(object = brain.H3K36me3,
            fragmentsGrange = fragments.interesting,
            cells = cells.to.plot,
            interestingRegion = interesting_region,
            window = window_bin,
            annotFilter = flt,
            fraction = fraction,
            annotation_colors = list('Cluster' = CTcolors),
            clusters_order = levels(brain.H3K4me3@active.ident)) # To have the order the same as in H3K4me3

print(p)

ensdb <- EnsDb.Mmusculus.v79
p2 <- ggbio::autoplot(ensdb,which=flt,names.expr="gene_name",mode='reduce') + 
   theme_bw() +   
   coord_cartesian(xlim=c(start(interesting_region),end(interesting_region))) + 
   theme(plot.margin = margin(t = 5.5, r = 0, b = 5.5, l = -20,unit="pt"))


png(file = paste0(params$out_prefix,'/Figures/figure2_src/H3K36me3_Sox10_heatmap.png'),width = 2048,height = 1024)
p
dev.off()



setEPS()
postscript(file =paste0(params$out_prefix,'/Figures/figure2_src/Sox10_gene_model.eps'),width = 8,height = 4)
p2
dev.off()
    
```




# Figure 2 markers on UMAP
```{r}
featurePlotMB <- function(object,feature,reduction = 'umap',slot='counts',title='feature',pt.size=0.1){
  data_to_plot            <- as.data.frame(Embeddings(object,reduction))
  data_to_plot$expression <- FetchData(object = object,vars = feature,slot = slot)[,1]
  
  colnames(data_to_plot)  <- c("dim_x","dim_y","expression")
  
  ggplot() + 
    geom_point(data=data_to_plot,aes(x=dim_x,y=dim_y),col="grey95",size=pt.size) +
    geom_point(data=data_to_plot[data_to_plot$expression > 0,],aes(x=dim_x,y=dim_y,col=expression),size=pt.size) +
    theme_void() +
    theme(panel.background = element_blank(),
          plot.title = element_text(size=40,face = 'bold',hjust = 0.5),legend.position = 'bottom'
          ) + 
#    xlab("UMAP 1") + ylab("UMAP 2") + 
    scale_color_viridis_c('',end = 0.7) + 
    ggtitle(title)
}


samples <- c("H3K4me3","H3K27ac","H3K36me3")
```

# H3K4me3

```{r}
colors <- CTcolors

brain.H3K4me3 <- readRDS(paste0(params$out_prefix,'H3K4me3',"/clustering/01.clustering.Rds"))


brain.H3K4me3$cell_type <- brain.H3K4me3@active.ident
DefaultAssay(brain.H3K4me3) <- "GA"

marker.genes <- c("Rfx4","Mog","Alx3","Nes","Pdgfra","Rbfox3","Gad1","Slc17a7","C1qa")

p <- list()
for(gene in marker.genes){
  plotData      <- FetchData(object = brain.H3K4me3,vars = gene,slot = 'data')
  #dynamic.range <- c(quantile(plotData[,1],0.05), quantile(plotData[,1],0.99))
  p[[gene]]     <- featurePlotMB(object = brain.H3K4me3,feature = gene,title = gene,pt.size = 0.5)
}

png(file = paste0(params$out_prefix,'/Figures/figure2_src/H3K4me3_UMAP_markers.png'),width = 3600,height=500)
do.call(grid.arrange,c(p,nrow=1))
dev.off()

ggplot(data=brain.H3K4me3@meta.data,aes(x=cell_type,y=logUMI)) + 
  geom_violin(aes(fill=cell_type)) + 
  geom_boxplot(width=0.05,outlier.shape = NA) + coord_cartesian(ylim=c(1,4.5))

ggplot(data=brain.H3K4me3[,brain.H3K4me3@active.ident != '4']@meta.data, aes(x=logUMI,y=cell_type,fill=cell_type))  + 
  geom_density_ridges() + 
  scale_fill_manual(values = CTcolors) + 
  coord_cartesian(xlim=c(1.5,4),ylim=c(1,10)) + theme_bw() + NoLegend() + 
  theme(text = element_text(size=24,face = 'bold')) + ylab("") + xlab("unique reads [log10]") + ggtitle("H3K4me3")


ggsave(filename =  paste0(params$out_prefix,'/Figures/figure3_src/H3K4me3_amounts.png'),width=6,height=6)
```



# H3K27me3

```{r}

brain.H3K27me3 <- readRDS(paste0(params$out_prefix,'H3K27me3',"/clustering/01.clustering.Rds"))

brain.H3K27me3$cell_type <- brain.H3K27me3@active.ident
#brain.H3K27me3$cell_type <- factor(brain.H3K27me3$cell_type,levels=c("Astrocytes","mOL","OEC","VLMC","OPC"))


DefaultAssay(brain.H3K27me3) <- "GA"

marker.genes <- c("Rfx4","Olig2","Pdgfra","Nkx6-2","Alx4","Neurod2","Gad1","Foxf2","Cttn")

p <- list()
for(gene in marker.genes){
  p[[gene]]     <- featurePlotMB(object = brain.H3K27me3,feature = gene,title = gene,pt.size = 0.5)
}

do.call(grid.arrange,c(p,nrow=1))

png(file = paste0(params$out_prefix,'/Figures/figure2_src/H3K27me3_UMAP_markers.png'),width = 3600,height=500)
do.call(grid.arrange,c(p,nrow=1))
dev.off()

ggplot(data=brain.H3K27me3@meta.data,aes(x=cell_type,y=logUMI)) + 
  geom_violin(aes(fill=cell_type)) + 
  scale_fill_manual(values = CTcolors) +
  geom_boxplot(width=0.05,outlier.shape = NA)+ coord_cartesian(ylim=c(0,3.5))


ggplot(data=brain.H3K27me3@meta.data, aes(x=logUMI,y=cell_type,fill=cell_type))  + 
  geom_density_ridges() + 
  scale_fill_manual(values = CTcolors) + 
  coord_cartesian(xlim=c(1.5,3.5),ylim=c(1,10)) +  theme_bw() + NoLegend() + 
  theme(text = element_text(size=24,face = 'bold')) + ylab("") + xlab("unique reads [log10]") + ggtitle("H3K27me3")

ggsave(filename = paste0(params$out_prefix,'/Figures/figure3_src/H3K27me3_amounts.png'),width=6,height=6)

```


# H3K27ac

```{r}
brain.H3K27ac           <- readRDS(paste0(params$out_prefix,'H3K27ac',"/clustering/01.clustering.Rds"))

brain.H3K27ac$cell_type <- brain.H3K27ac@active.ident
brain.H3K27ac$cell_type <- factor(brain.H3K27ac$cell_type,levels=c("Astrocytes","mOL","OEC","VLMC","OPC"))

DefaultAssay(brain.H3K27ac) <- "GA"

marker.genes <- c("Rfx4","Mog","Alx4","Gmds","Scrt1")

p <- list()
for(gene in marker.genes){
  p[[gene]]     <- featurePlotMB(object = brain.H3K27ac[,sample(colnames(brain.H3K27ac),5000)],feature = gene,title = gene,pt.size = 0.5)
}

do.call(grid.arrange,c(p,nrow=1))

png(file = paste0(params$out_prefix,'/Figures/figure2_src/H3K27ac_UMAP_markers.png'),width = 1800,height=500)
do.call(grid.arrange,c(p,nrow=1))
dev.off()


ggplot(data=brain.H3K27ac[,brain.H3K27ac@active.ident!='4']@meta.data,aes(x=cell_type,y=logUMI)) + 
  geom_violin(aes(fill=cell_type)) + 
  scale_fill_manual(values = CTcolors) + 
  geom_boxplot(width=0.05,outlier.shape = NA,fill='white') + 
  coord_cartesian(ylim=c(0,4.5))

ggplot(data=brain.H3K27ac[,brain.H3K27ac@active.ident != '4']@meta.data, aes(x=logUMI,y=cell_type,fill=cell_type))  + 
  geom_density_ridges() + 
  scale_fill_manual(values = CTcolors) + 
  coord_cartesian(xlim=c(1.5,4.5),ylim=c(1,7)) + theme_bw()+ NoLegend() + 
  theme(text = element_text(size=24,face = 'bold')) + ylab("") + xlab("unique reads [log10]") + ggtitle("H3K27ac")


ggsave(filename = paste0(params$out_prefix,'/Figures/figure3_src/H3K27ac_amounts.pdf'),width=6,height=4)
```


# H3K36me3

```{r}
brain.H3K36me3           <- readRDS(paste0(params$out_prefix,'H3K36me3',"/clustering/01.clustering.Rds"))

brain.H3K36me3$cell_type <- brain.H3K36me3@active.ident


DefaultAssay(brain.H3K36me3) <- "GA"
marker.genes <- c("Slc1a2","Mbp","Ptn","Tns3")

p <- list()
for(gene in marker.genes){
  p[[gene]]     <- featurePlotMB(object = brain.H3K36me3,feature = gene,title = gene,pt.size = 0.5)
}

do.call(grid.arrange,c(p,nrow=1))

png(file = paste0(params$out_prefix,'/Figures/figure2_src/H3K36me3_UMAP_markers.png'),width = 1500,height=500)
do.call(grid.arrange,c(p,nrow=1))
dev.off()

ggplot(data=brain.H3K36me3[,brain.H3K36me3@active.ident!='Unknown']@meta.data,aes(x=cell_type,y=logUMI)) + 
  scale_fill_manual(values = CTcolors) + 
  geom_violin(aes(fill=cell_type)) + 
  geom_boxplot(width=0.05,outlier.shape = NA)+ coord_cartesian(ylim=c(0,3.5))

ggplot(data=brain.H3K36me3[,!brain.H3K36me3@active.ident %in% c(4,5)]@meta.data, aes(x=logUMI,y=cell_type,fill=cell_type))  + 
  geom_density_ridges() + 
  scale_fill_manual(values = CTcolors) + 
  coord_cartesian(xlim=c(1.0,2.8),ylim=c(1,5)) + theme_bw()+ NoLegend() + 
  theme(text = element_text(size=24,face = 'bold')) + ylab("") + xlab("unique reads [log10]") + ggtitle("H3K36me3")

ggsave(filename = paste0(params$out_prefix,'/Figures/figure3_src/H3K36me3_amounts.pdf'),width=6,height=4)

```



