---
title: "R Notebook"
output: html_notebook
---




```{r}
order <- c("Astrocytes","mOL","OPC","OEC","Neurons_1","Neurons_2","Neurons_3","Microglia")


bw.files <- list.files(path = paste0(params$out_prefix,"H3K4me3/clustering/bigwig"),pattern=".bw",full.names = TRUE)
bw.files <- bw.files[unlist(lapply(order,function(x){grep(pattern = x, x= bw.files)}))]


bed.files <- list.files(path = paste0(params$out_prefix,"H3K4me3/clustering/markers_bed"),pattern=".bed",full.names = TRUE)
bed.files  <- bed.files[unlist(lapply(order,function(x){grep(pattern = x, x= bed.files)}))]

meta.command <- paste0('/usr/local/anaconda3/bin/computeMatrix reference-point ', ' -S ',paste(bw.files,collapse = " "), 
                                                                                  ' -R ',paste(bed.files,collapse = " "),
                                                                                  ' -a 10000',
                                                                                  ' -b 10000',
                                                                                  ' -p 4',
                                                                                  ' -o ',paste0(params$out_prefix,'Figures/figure4_src/H3K4me3_H3K4me3_metaplot.txt.gz'))

system(meta.command)

plot.command <- paste0('/usr/local/anaconda3/bin/plotHeatmap ', ' -m  ', paste0(params$out_prefix,'Figures/figureS6_src/H3K4me3_H3K4me3_metaplot.txt.gz'),
                                                                ' -o  ', paste0(params$out_prefix,'Figures/figureS6_src/H3K4me3_H3K4me3_metaplot.png'),
                                                                ' --colorList white,darkgreen',
                                                                ' --heatmapWidth 10',
                                                                ' --heatmapHeight 80',
                                                               # ' --zMax 10',
                                                                ' --zMin 5'
)

system(plot.command)

bed.files <- list.files(path = paste0(params$out_prefix,"Sten_RNA/marker_promoters/"),pattern="_promoters.bed",full.names = TRUE)

meta.command <- paste0('/usr/local/anaconda3/bin/computeMatrix reference-point ', ' -S ',paste(bw.files,collapse = " "), 
                                                                                  ' -R ',paste(bed.files,collapse = " "),
                                                                                  ' -a 10000',
                                                                                  ' -b 10000',
                                                                                  ' -p 4',
                                                                                  ' -o ',paste0(params$out_prefix,'Figures/figureS6_src/H3K4me3_H3K4me3_metaplot_RNA.txt.gz'))

system(meta.command)

plot.command <- paste0('/usr/local/anaconda3/bin/plotHeatmap ', ' -m  ', paste0(params$out_prefix,'Figures/figureS6_src/H3K4me3_H3K4me3_metaplot_RNA.txt.gz'),
                                                                ' -o  ', paste0(params$out_prefix,'Figures/figureS6_src/H3K4me3_H3K4me3_metaplot_RNA.png'),
                                                                ' --colorList white,darkgreen',
                                                                ' --heatmapWidth 10',
                                                                ' --heatmapHeight 80',
                                                               # ' --zMax 10',
                                                                ' --zMin 5'
)

system(plot.command)

```



# Pseudotime

```{r}
slingshot.result <- readRDS("~/mount/CT/git_test/results/H3K4me3/pseudotime/pseudotime_OLG_slingshot.Rds")
brain            <- readRDS("~/mount/CT/git_test/results/H3K4me3/pseudotime/pseudotime_OLG_final.Rds")

png(paste0(params$out_prefix,'/Figures/figureS6_src/pseudotime_PCA.png'),width=1200,height=400)
par(mfrow=c(1,3))
# Plot
cell_colors <- CTcolors[brain$cell_type]
plot(reducedDim(slingshot.result),col = cell_colors,pch=16,cex=0.5,axes=FALSE,main='',xlab="",ylab="")
lines(slingshot.result, lwd = 2,  col = 'black')

# Pseudotime
pt <- slingPseudotime(slingshot.result)

cell_colors = viridis(100,option = "B")[cut(pt[,1],breaks=100)]
plot(reducedDim(slingshot.result),col=cell_colors,pch=16,cex=0.5,axes=FALSE,main='',xlab="",ylab="")
lines(slingshot.result, lwd = 2,  col = 'black')

# mOL signature
cell_colors <- viridis(100)[Hmisc::cut2(brain$marker_Sox10_Oligodendrocytes / brain$marker_Oligodendrocyte.precursor.cells,g = 100)]
plot(reducedDim(slingshot.result)[,1:2],col=cell_colors,pch=16,cex=0.5,axes=FALSE,main='',xlab="",ylab="")
lines(slingshot.result, lwd = 2,  col = 'black')
dev.off()

FeaturePlot(brain,'pseudotime') + scale_color_viridis(option = 'B') + NoAxes() + ggtitle('')
ggsave(paste0(params$out_prefix,'/Figures/figureS6_src/pseudotime_UMAP.png'),width = 5,height = 5)

FeaturePlot(brain,'marker_Sox10_Oligodendrocytes',max.cutoff = 0.06) + scale_color_viridis(option = 'D') + NoAxes() + ggtitle('')
ggsave(paste0(params$out_prefix,'/Figures/figureS6_src/OL_signature_UMAP.png'),width = 5,height = 5)
```


















