---
title: "R Notebook"
output: html_notebook
params:
  out_prefix: "~/mount/CT/git_test/results/"
---


```{r}
library(Seurat)
library(Signac)
library(ggplot2)
library(Matrix)
library(GenomicRanges)
library(gridExtra)
library(reshape2)
```

```{r}
clusters_order <- c("Astrocytes","VLMC","mOL","Neurons_1","Neurons_2","Neurons_3","OEC","OPC","Microglia")

# Colors definition - consistent accross the paper
CTcolors        <- scales::hue_pal()(9)
names(CTcolors) <- clusters_order
```


```{r}
brain.Olig2 <- readRDS(paste0(params$out_prefix,'Olig2/clustering/01.clustering.Rds'))
brain.Rad21 <- readRDS(paste0(params$out_prefix,'Rad21/clustering/01.clustering.Rds'))
```

```{r}
markers     <- read.csv2(file=paste0(params$out_prefix,"/H3K4me3/clustering/markers.csv"))
markers.pos <- markers[markers$p_val_adj < 0.05 & markers$avg_logFC > 0,]

```

```{r,fig.width=6,fig.height=6}
DefaultAssay(brain.Olig2) <- 'bins_5000'

marker.signatures <- lapply(unique(markers$cluster),function(x){
  markers.x      <- markers.pos[markers.pos$cluster == x,]
  markers.x      <- head(markers.x,500)
  markers.ranges <- subsetByOverlaps(x      = StringToGRanges(rownames(brain.Olig2)),
                                     ranges = StringToGRanges(markers.x$X))
  counts.out <- Matrix::colSums(brain.Olig2[['bins_5000']]@counts[which(rownames(brain.Olig2) %in% GRangesToString(markers.ranges)),])
  counts.out / 10^brain.Olig2$logUMI[names(counts.out)]
})

names(marker.signatures) <- unique(markers$cluster)
marker.signatures.df     <- as.data.frame(do.call(cbind,marker.signatures))

brain.Olig2 <- AddMetaData(brain.Olig2,marker.signatures.df)

p.ls <- lapply(colnames(marker.signatures.df),function(x){FeaturePlot(brain.Olig2,
              x,
              max.cutoff = ifelse(quantile(brain.Olig2@meta.data[,x],0.9) > 0,
                                  yes = quantile(brain.Olig2@meta.data[,x],0.9),
                                  no  = max(brain.Olig2@meta.data[,x])),
              pt.size = 0.25) + 
    scale_color_viridis_c()+
    ggtitle(paste0(x,' signature (promoters)'))
})
png(filename = paste0(params$out_prefix,'/Figures/figureS7_src/Olig2_UMAP_markers.png'),width=9,height=9,units = 'in',res=300)
do.call(grid.arrange,c(p.ls[c(1,2,3,4,6)],ncol=2))
dev.off()
```

```{r}
marker.signatures.df$cell_type <- brain.Olig2$cell_type[rownames(marker.signatures.df)]
marker.signatures.plot <- marker.signatures.df[,c("Astrocytes","mOL","VLMC","OEC","OPC","cell_type")]

ggplot(data = melt(marker.signatures.plot,id.vars = 'cell_type')) + 
  geom_boxplot(aes(x=variable,y=value,fill=cell_type),outlier.shape=NA) + 
  theme_bw() + 
  coord_cartesian(ylim=c(0,0.08)) + 
  scale_fill_manual(values = c('oligo' = unname(CTcolors[3]),'non_oligo' = unname(CTcolors[1]))) + 
  theme(axis.text.x = element_text(face = 'bold',size = 16,hjust = 1,angle = 45),
        legend.title = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())  

ggsave(filename = paste0(params$out_prefix,'/Figures/figureS7_src/Olig2_signatures_boxplot.png'),width=6,height = 4)
```



```{r,fig.width=6,fig.height=6}
assay                     <- 'bins_25000'
DefaultAssay(brain.Rad21) <- assay

marker.signatures <- lapply(unique(markers$cluster),function(x){
  markers.x      <- markers.pos[markers.pos$cluster == x,]
  markers.x      <- head(markers.x,500)
  markers.ranges <- subsetByOverlaps(x      = StringToGRanges(rownames(brain.Rad21)),
                                     ranges = StringToGRanges(markers.x$X))
  counts.out <- Matrix::colSums(brain.Rad21[[assay]]@counts[which(rownames(brain.Rad21) %in% GRangesToString(markers.ranges)),])
  counts.out / 10^brain.Rad21$logUMI[names(counts.out)]
})

names(marker.signatures) <- unique(markers$cluster)
marker.signatures.df     <- as.data.frame(do.call(cbind,marker.signatures))

brain.Rad21 <- AddMetaData(brain.Rad21,marker.signatures.df)

p.ls <- lapply(colnames(marker.signatures.df),function(x){FeaturePlot(brain.Rad21,
              x,
              max.cutoff = ifelse(quantile(brain.Rad21@meta.data[,x],0.9) > 0,
                                  yes = quantile(brain.Rad21@meta.data[,x],0.9),
                                  no  = max(brain.Rad21@meta.data[,x])),
              pt.size = 1) + 
    scale_color_viridis_c() + 
    ggtitle(paste0(x,' signature (promoters)'))
})

png(filename = paste0(params$out_prefix,'/Figures/figureS7_src/Rad21_UMAP_markers.png'),width=9,height=9,units = 'in',res=300)
do.call(grid.arrange,c(p.ls[c(1,2,3,4,6)],ncol=2))
dev.off()
```

```{r}
marker.signatures.df$cell_type <- as.character(brain.Rad21$cell_type[rownames(marker.signatures.df)])
marker.signatures.df           <- marker.signatures.df[marker.signatures.df$cell_type != "Unknown",]

marker.signatures.plot <- marker.signatures.df[,c("Astrocytes","mOL","OEC","OPC","cell_type")]



ggplot(data = melt(marker.signatures.plot,id.vars = 'cell_type')) + 
  geom_boxplot(aes(x=variable,y=value,fill=cell_type),outlier.shape=NA) + 
  theme_bw() + 
  coord_cartesian(ylim=c(0,0.08)) + 
  scale_fill_manual(values = CTcolors) + 
  theme(axis.text.x = element_text(face = 'bold',size = 16,hjust = 1,angle = 45),
        legend.title = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())
ggsave(filename = paste0(params$out_prefix,'/Figures/figureS7_src/Rad21_signatures_boxplot.png'),width=6,height = 4)

```



```{r}
integrated <- readRDS(paste0(params$out_prefix,'Olig2/integration/integrated.Rds'))

p1 <- DimPlot(integrated[,integrated$antibody == "Olig2"]) + NoAxes() + NoLegend() + scale_color_manual(values = c('oligo' = unname(CTcolors[3]),'non_oligo' = unname(CTcolors[1])))
p2 <- DimPlot(integrated[,integrated$antibody == "H3K27ac"]) + NoAxes() + NoLegend() + scale_color_manual(values=CTcolors)
ggsave(filename = paste0(params$out_prefix,'/Figures/figureS7_src/Olig2_integration_UMAP.png'),width=10,height =5,plot = p1+p2)
```




```{r}
integrated <- readRDS(paste0(params$out_prefix,'Rad21/integration/integrated.Rds'))

p1 <- DimPlot(integrated[,integrated$antibody == "Rad21"]) + NoAxes() + NoLegend() + scale_color_manual(values=CTcolors)
p2 <- DimPlot(integrated[,integrated$antibody == "H3K27ac"]) + NoAxes() + NoLegend() + scale_color_manual(values=CTcolors)
ggsave(filename = paste0(params$out_prefix,'/Figures/figureS7_src/Rad21_integration_UMAP.png'),width=14,height =7,plot = p1+p2)
```



