---
title: "R Notebook"
output: html_notebook
params:
  out_prefix: '~/mount/CT/git_test/results/'  

---

```{r}
library(Seurat)
library(ggplot2)
library(pheatmap)

# order clusters
clusters_order <- c("Astrocytes","VLMC","mOL","Neurons_1","Neurons_2","Neurons_3","OEC","OPC","Microglia")

# Colors definition - consistent accross the paper
CTcolors        <- scales::hue_pal()(9)
names(CTcolors) <- clusters_order


samples <- c("H3K4me3","H3K27ac","H3K36me3","H3K27me3")
dir.create( paste0(params$out_prefix,'Figures/figureS2_src/'))
```

```{r, fig.width=2,fig.height=2}
brain.ls <- lapply(samples,function(x){
  #file.exists(paste0(params$out_prefix,x,"/clustering/01.clustering.Rds"))
  brain <- readRDS(paste0(params$out_prefix,x,"/clustering/01.clustering.Rds"))
  return(brain)
})

nfeature.ls <- lapply(brain.ls,function(x){
  x@meta.data[,grep('nFeature_bins_',colnames(x@meta.data))]
})

names(nfeature.ls) <- samples

nfeature.ls <- lapply(seq(nfeature.ls),function(x){
  out        <- data.frame('nfeatures' = nfeature.ls[[x]])
  out$sample <- names(nfeature.ls)[x]
  out
})


nfeature.df <- do.call(rbind,nfeature.ls)
nfeature.df$sample <- factor(nfeature.df$sample,levels=samples)


p <- ggplot(data=nfeature.df) + geom_histogram(aes(x=nfeatures,fill=sample),binwidth=40) + facet_wrap(~sample) + theme_bw() + coord_cartesian(xlim=c(0,1000)) + scale_fill_brewer(palette = "Set1") + NoLegend() + theme(text= element_text(size=24,face = 'bold'),axis.text.x = element_text(size=16))

print(p)

ggsave(filename = paste0(params$out_prefix,'Figures/figureS2_src/nFeatures.pdf'),plot = p,width=6,height = 6)

```

```{r,fig.width=9,fig.height=9}
library(RColorBrewer)
library(scales)

colors.base <- brewer.pal(n=9, name = "Set1")

col.GFP <- c("GFP+" = colors.base[3],"GFP-" = colors.base[4])
col.Age <- c("P15"  = colors.base[1],"P25"  = colors.base[2])

  
p.ls <- lapply(brain.ls,function(x){
  p1 <- DimPlot(x,group.by = 'GFP', pt.size=0.01) + scale_color_manual(values = col.GFP)  + NoAxes() + theme(legend.position = 'bottom',legend.text = element_text(size = 8,face='bold'))
  p2 <- DimPlot(x,group.by = 'Age', pt.size=0.01) + scale_color_manual(values = col.Age)  + NoAxes() + theme(legend.position = 'bottom',legend.text = element_text(size = 8,face='bold'))
  p3 <- DimPlot(x,group.by = 'sample', pt.size=0.01)+ NoAxes() + theme(legend.position = 'bottom',legend.text = element_text(size = 8,face='bold'))
  return(list(p1,p2,p3))
})

p.ls <- unlist(p.ls,recursive = FALSE)
do.call(grid.arrange,c(p.ls,'ncol'=3))

png(filename = paste0(params$out_prefix,'/Figures/figureS2_src/UMAP_GFP_Age_replicates.png'),width = 15,height = 15,units = 'in',res = 300)
do.call(grid.arrange,c(p.ls,'ncol'=3))
dev.off()
```

```{r}

p1 <- ggplot(data=brain.ls[[1]]@meta.data[,c("Age","GFP",'cell_type')]) + 
  geom_bar(aes(fill = GFP, x = cell_type)) + 
  theme_bw() + 
  scale_fill_manual(values = col.GFP) + 
  theme(text=element_text(size=18,face='bold'),
        axis.text.x = element_text(angle=45,hjust=1),legend.title = element_blank(),axis.title.x = element_blank()) 

ggsave(filename = paste0(params$out_prefix,"Figures/figureS2_src/GFP_barplot.png"),plot = p1,width = 5,height = 4)


p2 <- ggplot(data=brain.ls[[1]]@meta.data[,c("Age","GFP",'cell_type')]) + 
  geom_bar(aes(fill = Age, x = cell_type)) + 
  theme_bw() + 
  scale_fill_manual(values = col.Age) +
  theme(text=element_text(size=18,face='bold'),
        axis.text.x = element_text(angle=45,hjust=1),legend.title = element_blank(),axis.title.x = element_blank()) 


ggsave(filename = paste0(params$out_prefix,"Figures/figureS2_src/Age_barplot.png"),plot = p2,width = 5,height = 4)
```

