---
title: "R Notebook"
output: html_notebook
params:
  out_prefix: "~/mount/CT/git_test/results/"
---

```{r}
library(Seurat)
library(ggplot2)
library(dplyr)
library(gridExtra)
```

```{r}
# order clusters
clusters_order <- c("Astrocytes","VLMC","mOL","Neurons_1","Neurons_2","Neurons_3","OEC","OPC","Microglia")

# Colors definition - consistent accross the paper
CTcolors        <- scales::hue_pal()(9)
names(CTcolors) <- clusters_order

```

# Metagene H3K27me3 around H3K4me3 modified genes

```{R some_shitty_code}
# conda activate CT_snakemake

bw.files <- list.files(path = paste0(params$out_prefix,"H3K27me3/clustering/bigwig"),pattern=".bw",full.names = TRUE)
bw.files <- bw.files[c(1,3,7,6,4,5,2)]

bed.files <- list.files(path = paste0(params$out_prefix,"H3K4me3/clustering/markers_bed"),pattern=".bed",full.names = TRUE)
bed.files <- bed.files[c(1,3,8,7,4,5,6,2)]

                      

meta.command <- paste0('computeMatrix reference-point ', ' -S ',paste(bw.files,collapse = " "), 
                                                         ' -R ',paste(bed.files,collapse = " "),
                                                         ' -a 10000',
                                                         ' -b 10000',
                                                         ' -p 4',
                                                         ' -o ',paste0(params$out_prefix,'Figures/figure3_src/H3K4me3_H3K27me3_metaplot.txt.gz'))

system(meta.command)

plot.command <- paste0('plotHeatmap ', ' -m  ', paste0(params$out_prefix,'Figures/figure3_src/H3K4me3_H3K27me3_metaplot.txt.gz'),
                                       ' -o  ', paste0(params$out_prefix,'Figures/figure3_src/H3K4me3_H3K27me3_metaplot.pdf'),
                                       ' --colorList white,darkred',
                                       ' --heatmapWidth 10',
                                       ' --heatmapHeight 80',
                                       ' --zMax 10',
                                       ' --zMin 2')

system(plot.command)
```

```{R some_shitty_code_2}
# conda activate CT_snakemake

bw.files <- list.files(path = paste0(params$out_prefix,"H3K4me3/clustering/bigwig"),pattern=".bw",full.names = TRUE)
bw.files <- bw.files[c(1,3,8,7,4,5,6,2)]

bed.files <- list.files(path = paste0(params$out_prefix,"H3K4me3/clustering/markers_bed"),pattern=".bed",full.names = TRUE)
bed.files <- bed.files[c(1,3,8,7,4,5,6,2)]

                      

meta.command <- paste0('computeMatrix reference-point ', ' -S ',paste(bw.files,collapse = " "), 
                                                         ' -R ',paste(bed.files,collapse = " "),
                                                         ' -a 10000',
                                                         ' -b 10000',
                                                         ' -p 4',
                                                         ' -o ',paste0(params$out_prefix,'Figures/figure3_src/H3K4me3_H3K4me3_metaplot.txt.gz'))

system(meta.command)

plot.command <- paste0('plotHeatmap ', ' -m  ', paste0(params$out_prefix,'Figures/figure3_src/H3K4me3_H3K4me3_metaplot.txt.gz'),
                                       ' -o  ', paste0(params$out_prefix,'Figures/figure3_src/H3K4me3_H3K4me3_metaplot.pdf'),
                                       ' --colorList white,darkgreen',
                                       ' --heatmapWidth 10',
                                       ' --heatmapHeight 80',
                                       ' --zMax 10',
                                       ' --zMin 2')

system(plot.command)
```




# Integration 3 active

```{r,fig.width=12,fig.height=4}
brain <- readRDS(paste0(params$out_prefix,'integration/histone_3active/histone_3active_integrated.Rds'))

clusters <- c("mOL",
              "Astrocytes",
              "OEC",
              "OPC",
              "VLMC")

brain <- brain[,brain$cell_type %in% clusters]

p1 <- DimPlot(brain[,brain$antibody == "H3K4me3"]) + scale_color_manual(values = CTcolors)  + NoLegend() + NoAxes()
p2 <-  DimPlot(brain[,brain$antibody == "H3K27ac"]) + scale_color_manual(values = CTcolors) + NoLegend() + NoAxes()
p3 <- DimPlot(brain[,brain$antibody == "H3K36me3"]) + scale_color_manual(values = CTcolors) + NoLegend() + NoAxes()

p1+p2+p3
ggsave(p1+p2+p3,filename = paste0(params$out_prefix,'Figures/figure3_src/3active_integrated.png'),width=12,height = 4)
```

```{r,fig.width=8,fig.height=4}
integrated <- readRDS(paste0(params$out_prefix,'integration/H3K4me3_RNA/H3K4me3_RNA_coembed.Rds'))

integrated$antibody[is.na(integrated$antibody)] <- "RNA"


DimPlot(integrated,group.by='antibody') + scale_color_brewer(palette = 'Set1')

p1 <- DimPlot(integrated[,integrated$antibody == 'H3K4me3'],group.by = 'cell_type') + NoLegend() + NoAxes() + scale_color_manual(values = CTcolors)
p2 <- DimPlot(integrated[,integrated$antibody == 'RNA'],group.by = 'cell_type') + NoLegend() + NoAxes()

p1 + p2

ggsave(p1+p2,filename = paste0(params$out_prefix,'Figures/figure3_src/H3K4me3_RNA_coembeding.png'),width=8,height=4)
```



```{r}
integrated <- readRDS(paste0(params$out_prefix,"integration/H3K4me3_marques/H3K4me3_marques_coembed.Rds"))
markers    <- read.csv2(paste0(params$out_prefix,"marques_RNA/clustering/markers_merged_clusters.csv"))
#markers    <- read.csv2(paste0(params$out_prefix,"marques_RNA/clustering/markers.csv"))


p1 <- DimPlot(integrated[,integrated$antibody=="RNA-seq"])
p2 <-DimPlot(integrated[,integrated$antibody=='H3K4me3'])
p1+p2
```


```{r}
markers.pos <- markers %>% group_by(cluster) %>% dplyr::filter(p_val_adj < 0.05 & avg_logFC > 0) %>% dplyr::top_n(n = 200,wt = p_val_adj)

cluster.scores.ls <- lapply(unique(markers.pos$cluster),function(x){
  markers.x <- markers.pos[markers.pos$cluster==x,]
  genes.x   <- markers.x$gene
  Matrix::colSums(integrated[['GA']]@counts[rownames(integrated[['GA']]) %in% genes.x,]) / 10^integrated$logUMI
})



cluster.scores           <- as.data.frame(do.call(cbind,cluster.scores.ls))
colnames(cluster.scores) <- unique(markers.pos$cluster)

integrated <- AddMetaData(integrated,cluster.scores)


p.ls <- lapply(colnames(cluster.scores),function(x){
  integrated.x <- integrated[,integrated$antibody == "H3K4me3"] 
  FeaturePlot(object = integrated.x,features = x,max.cutoff = quantile(integrated.x@meta.data[,x],0.95),min.cutoff = quantile(integrated.x@meta.data[,x],0.1)) + 
    #scale_color_gradient2(low = 'blue',mid='white',high = 'red',midpoint = median(integrated.x@meta.data[,x])) + 
    scale_color_viridis_c() + 
    theme(legend.position = 'bottom',legend.text = element_text(size=8),
          legend.key.width = unit(x = 30, units='points'),
          legend.key.height = unit(x=5, units='points')) + NoAxes() #+ ggtitle("")
})


p.ls

RNA.colors        <- c(scales::hue_pal()(length(levels(brain.RNA@active.ident))),"#D3D3D3")
names(RNA.colors) <- c(levels(brain.RNA@active.ident),"other")


p.RNA.ls <- lapply(colnames(cluster.scores),function(x){
  brain.RNA.x                 <- integrated[,integrated$antibody == 'RNA-seq']
  brain.RNA.x$current_cluster <- "other"
  brain.RNA.x$current_cluster[brain.RNA.x@active.ident == x] <- x
  DimPlot(brain.RNA.x,group.by='current_cluster',pt.size = 1) + 
    scale_color_manual(values = RNA.colors) + 
    NoAxes() + 
    theme(legend.position = 'bottom',
          legend.text = element_text(size=12),
          legend.key.width = unit(x = 20, units='points'),
          legend.key.height = unit(x=5, units='points'))
})

p.RNA.ls
```


```{r, fig.width=10,fig.height=4}
p     <- do.call(grid.arrange,c(c(p.ls[c(1,4,11,9,5)],c(p.RNA.ls[c(1,4,11,9,5)])),nrow=2))

p1 <- DimPlot(integrated[,integrated$antibody == "RNA-seq"])+ NoAxes() + NoLegend()
p2 <- DimPlot(integrated[,integrated$antibody == "H3K4me3"])+ NoAxes() + NoLegend() + scale_color_manual(values = CTcolors)
p1+p2

ggsave(plot = p,filename = paste0(params$out_prefix,'Figures/figure3_src/Oligo_coembeding_markers.png'),width=14,height=5)
ggsave(plot= p2+ p1, filename = paste0(params$out_prefix,'Figures/figure3_src/Oligo_RNA_UMAP.png'),width=6,height=3)
```


######### GGridges plots

## See figure2 scripts



