---
title: "R Notebook"
output: html_notebook
params:
  out_prefix: "~/mount/CT/git_test/results/"
---

```{r}
library(Seurat)
library(ggplot2)
library(gridExtra)
```

```{r}
markers <- read.csv2(paste0(params$out_prefix,'Sten_RNA/clustering/sten_RNA_markers.csv'))
markers$cluster <- gsub(" ","_",markers$cluster)
markers.pos <- markers[markers$p_val < 0.05 & markers$avg_logFC > 0,]

```



```{r}
assay = "GA"

samples = c("H3K4me3","H3K27ac","H3K36me3","H3K27me3")

brain.ls <- lapply(samples,function(x){
    brain <- readRDS(paste0(params$out_prefix,x,'/clustering/01.clustering.Rds'))
})
```

```{r}
clusters_to_use <- c(
  "Astrocytes",
  "Microglia",
  "Non-glutamatergic_neuroblasts",
  "Olfactory_ensheathing_cells",
  "Oligodendrocyte_precursor_cells",
  "Oligodendrocytes",
  "Telencephalon_projecting_excitatory_neurons",
  "Telencephalon_projecting_inhibitory_neurons",
  "Vascular_and_leptomeningeal_cells"
)

clusters_to_use <- gsub("-",".",clusters_to_use)
clusters_to_use <- clusters_to_use[c(1,6,5,4,9,2,3,7,8)]
```


```{r}
plots.ls <- lapply(brain.ls,function(brain){

  brain.markers.ls <- lapply(unique(markers$cluster),function(x){
    marker.genes <- markers[markers$cluster==x & markers$p_val_adj < 0.05 & markers$avg_logFC > 0,"gene"]
    marker.genes <- head(marker.genes,200)
    marker.genes.agg.exp <- Matrix::colSums(brain[[assay]]@data[rownames(brain[[assay]]) %in% marker.genes,])
    marker.genes.agg.exp <- marker.genes.agg.exp / Matrix::colSums(brain[[assay]]@counts)
    return(marker.genes.agg.exp)
  })
  
  names(brain.markers.ls)  <- gsub("-",".",unique(markers$cluster))
  markers.agg.df           <- do.call(cbind,brain.markers.ls)
  #colnames(markers.agg.df) <- paste0("marker_",gsub(" ",".",colnames(markers.agg.df)))
  
  print(head(markers.agg.df))
  
  brain <- AddMetaData(brain,metadata = markers.agg.df,col.name = colnames(markers.agg.df))
  
  lapply(clusters_to_use,function(x){
    FeaturePlot(brain,x,max.cutoff = quantile(markers.agg.df[,x],0.9,na.rm=TRUE),min.cutoff = quantile(markers.agg.df[,x],0.3,na.rm=TRUE),pt.size = 0.5) + 
      scale_color_viridis_c() + ggtitle(gsub("_|\\."," ",x)) + theme(text = element_text(face = 'bold',size=26))
      #scale_color_gradient2(low = 'blue',mid='white',high='red',midpoint = quantile(markers.agg.df[,x],0.6)) 
    })
})




plots.merged.ls <- lapply(plots.ls,function(x){
  do.call(grid.arrange,x)
})

lapply(seq(plots.merged.ls),function(x){
  png(paste0(params$out_prefix,"/Figures/figureS4_src/",samples[x],".png"),width = 2000,height=2000) 
  plot(plots.merged.ls[[x]])
  dev.off()})
```

