---
title: "R Notebook"
output:
  html_document:
    df_print: paged
params:
  out_prefix: "~/mount/CT/git_test/results/"
---

```{r}
library(Seurat)
library(ggplot2)

set.seed(2020)


# order clusters
clusters_order <- c("Astrocytes","VLMC","mOL","Neurons_1","Neurons_2","Neurons_3","OEC","OPC","Microglia")

# Colors definition - consistent accross the paper
CTcolors        <- scales::hue_pal()(9)
names(CTcolors) <- clusters_order
```


```{r}
brain.RNA  <- readRDS(paste0(params$out_prefix,"/Sox10_RNA/clustering/GFP/01.clustering.Rds"))
sten.RNA   <- readRDS(paste0(params$out_prefix,"/Sten_RNA/clustering/01.clustering_20000cells.Rds"))

brain.RNA$dataset <- "Sox10_GFP+"
sten.RNA$dataset  <- "SL_atlas_20k"

sten.RNA <- sten.RNA[,-grep("Enteric|Peripher|Schwann", sten.RNA$TaxonomyRank4) ]

brain.list <- list(brain.RNA,sten.RNA)

common.genes <- intersect(rownames(brain.RNA),rownames(sten.RNA))

for (i in 1:length(brain.list)) {
    brain.list[[i]] <- NormalizeData(brain.list[[i]], verbose = FALSE)
    brain.list[[i]] <- FindVariableFeatures(brain.list[[i]], selection.method = "vst", 
        nfeatures = 2000, verbose = FALSE)
}
```

```{r,fig.width=8,fig.height=8}

brain.anchors    <- FindIntegrationAnchors(object.list = brain.list, dims = 1:30)
brain.integrated <- IntegrateData(anchorset = brain.anchors, dims = 1:30)


brain.integrated <- ScaleData(brain.integrated, verbose = FALSE)
brain.integrated <- FindVariableFeatures(brain.integrated)

brain.integrated <- RunPCA(brain.integrated, npcs = 30, verbose = FALSE)
brain.integrated <- RunUMAP(brain.integrated, reduction = "pca", dims = 1:30)

DimPlot(brain.integrated, group.by = "dataset",label=TRUE,pt.size = 0.01) + NoLegend() + scale_color_brewer(palette = 'Set1')
```

```{r, fig.width=16,fig.height=8}
p1 <- DimPlot(brain.integrated[,brain.integrated$dataset == "Sox10_GFP+"],label=TRUE,pt.size = 0.01) + NoLegend()
p2 <- DimPlot(brain.integrated[,brain.integrated$dataset == "SL_atlas_20k"],label=TRUE,repel=TRUE,pt.size = 0.01,group.by = 'TaxonomyRank4') + NoLegend() 
p1+p2
```


```{r}
saveRDS(object = brain.integrated,file = paste0(params$out_prefix,"Sox10_RNA/integration/scRNA_integrated.Rds"))
```

