---
title: "R Notebook"
output: html_notebook
params:
  out_prefix: "~/mount/CT/git_test/results"

---

```{r libraries}
library(Seurat)
library(EnsDb.Mmusculus.v79)
library(ensembldb)
library(rtracklayer)
```

```{r load_data}
markers <- read.csv2(paste0(params$out_prefix,"/Sten_RNA/clustering/sten_RNA_markers.csv"))
```

```{r select_clusters}
markers$cluster <- gsub(" ","_",markers$cluster)
markers.pos <- markers[markers$p_val < 0.05 & markers$avg_logFC > 0,]


clusters_to_use <- c(
  "01.Astrocytes",
  "02.Oligodendrocytes",
  "03.Olfactory_ensheathing_cells",
  "04.Oligodendrocyte_precursor_cells",
  "05.Vascular_and_leptomeningeal_cells",
  "06.Non-glutamatergic_neuroblasts",
  "07.Telencephalon_projecting_excitatory_neurons",
  "08.Telencephalon_projecting_inhibitory_neurons",
  "09.Microglia"
  )


```

```{r export_promoters}
conversion.table <- as.data.frame(genes(EnsDb.Mmusculus.v79))[,c("gene_name","symbol")]

genes.promoters <- promoters(EnsDb.Mmusculus.v79)
genes.promoters <- genes.promoters[genes.promoters$tx_biotype %in% c("protein_coding","lincRNA")]
genes.promoters$symbol <- conversion.table[genes.promoters$gene_id,"symbol",drop=TRUE]

lapply(clusters_to_use,function(x){
  markers.x <- markers.pos[markers.pos$cluster == gsub("[0-9]+.","",x),]
  markers.x <- head(markers.x,100)
  promoters.x <- genes.promoters[genes.promoters$symbol %in% markers.x$gene]
  rtracklayer::export(object = promoters.x,con = paste0(params$out_prefix,"/Sten_RNA/marker_promoters/",x,"_promoters.bed"))
})

```

```{r}
genes.genes <- genes(EnsDb.Mmusculus.v79)
genes.genes <- genes.genes[genes.genes$gene_biotype %in% c("protein_coding","lincRNA"),]

lapply(clusters_to_use,function(x){
  markers.x <- markers.pos[markers.pos$cluster == gsub("[0-9]+.","",x),]
  markers.x <- head(markers.x,100)
  genes.x <- genes.genes[genes.genes$symbol %in% markers.x$gene]
  rtracklayer::export(object = genes.x,con = paste0(params$out_prefix,"/Sten_RNA/marker_promoters/",x,"_genes.bed"))
})

```













